local ui = {} 
function ui.init(parent)
local Node = GUI:Node_Create(parent, "Node", 0, 0)

local Panel_1 = GUI:Layout_Create(Node, "Panel_1", 0, 0, 416, 608, false)
GUI:Layout_setBackGroundColorOpacity(Panel_1, 255)
GUI:Layout_setBackGroundImage(Panel_1, "")
GUI:setTag(Panel_1, 31)

local Image_20 = GUI:Image_Create(Panel_1, "Image_20", 0, 0, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_juese_03.png")
GUI:setContentSize(Image_20, 416, 608)
GUI:setTag(Image_20, 213)

local Image_bg1 = GUI:Image_Create(Panel_1, "Image_bg1", 112, 585, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:Image_setScale9Enabled(Image_bg1, true)
GUI:Image_setScale9Slice(Image_bg1, 35, 35, 7, 5)
GUI:setAnchorPoint(Image_bg1, 0, 1)
GUI:setContentSize(Image_bg1, 130, 70)
GUI:setTag(Image_bg1, 275)

local Image_bg2 = GUI:Image_Create(Panel_1, "Image_bg2", 322, 335, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_1.png")
GUI:setAnchorPoint(Image_bg2, 0.5, 0.5)
GUI:setContentSize(Image_bg2, 153, 281)
GUI:setTag(Image_bg2, 291)

local nd_button = GUI:Layout_Create(Panel_1, "nd_button", 0, 0, 412, 608, false)
GUI:Layout_setBackGroundColorOpacity(nd_button, 255)
GUI:Layout_setBackGroundImage(nd_button, "")

local ScrollView_att = GUI:ScrollView_Create(Panel_1, "ScrollView_att", 252, 202, 142, 270, 1)
GUI:Layout_setBackGroundColorOpacity(ScrollView_att, 255)
GUI:Layout_setBackGroundImage(ScrollView_att, "")
GUI:Layout_setClippingEnabled(ScrollView_att, true)
GUI:ScrollView_setInnerContainerSize(ScrollView_att, 500, 270)
GUI:setTouchEnabled(ScrollView_att, true)

local Panel_att_item_1 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_1", 0, 243, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_1, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_1, "")
GUI:setTag(Panel_att_item_1, 1)

local Text_z = GUI:Text_Create(Panel_att_item_1, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

local Image_att = GUI:Image_Create(Panel_att_item_1, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

local Text_bas = GUI:Text_Create(Panel_att_item_1, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att_item_2 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_2", 0, 216, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_2, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_2, "")
GUI:setTag(Panel_att_item_2, 2)

Text_z = GUI:Text_Create(Panel_att_item_2, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

Image_att = GUI:Image_Create(Panel_att_item_2, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

Text_bas = GUI:Text_Create(Panel_att_item_2, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att_item_3 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_3", 0, 189, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_3, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_3, "")
GUI:setTag(Panel_att_item_3, 3)

Text_z = GUI:Text_Create(Panel_att_item_3, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

Image_att = GUI:Image_Create(Panel_att_item_3, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

Text_bas = GUI:Text_Create(Panel_att_item_3, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att_item_4 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_4", 0, 162, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_4, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_4, "")
GUI:setTag(Panel_att_item_4, 4)

Text_z = GUI:Text_Create(Panel_att_item_4, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

Image_att = GUI:Image_Create(Panel_att_item_4, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

Text_bas = GUI:Text_Create(Panel_att_item_4, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att_item_5 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_5", 0, 135, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_5, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_5, "")
GUI:setTag(Panel_att_item_5, 5)

Text_z = GUI:Text_Create(Panel_att_item_5, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

Image_att = GUI:Image_Create(Panel_att_item_5, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

Text_bas = GUI:Text_Create(Panel_att_item_5, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att_item_6 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_6", 0, 108, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_6, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_6, "")
GUI:setTag(Panel_att_item_6, 6)

Text_z = GUI:Text_Create(Panel_att_item_6, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

Image_att = GUI:Image_Create(Panel_att_item_6, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

Text_bas = GUI:Text_Create(Panel_att_item_6, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att_item_7 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_7", 0, 81, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_7, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_7, "")
GUI:setTag(Panel_att_item_7, 7)

Text_z = GUI:Text_Create(Panel_att_item_7, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

Image_att = GUI:Image_Create(Panel_att_item_7, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

Text_bas = GUI:Text_Create(Panel_att_item_7, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att_item_8 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_8", 0, 54, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_8, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_8, "")
GUI:setTag(Panel_att_item_8, 8)

Text_z = GUI:Text_Create(Panel_att_item_8, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

Image_att = GUI:Image_Create(Panel_att_item_8, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

Text_bas = GUI:Text_Create(Panel_att_item_8, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att_item_9 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_9", 0, 27, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_9, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_9, "")
GUI:setTag(Panel_att_item_9, 9)

Text_z = GUI:Text_Create(Panel_att_item_9, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

Image_att = GUI:Image_Create(Panel_att_item_9, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

Text_bas = GUI:Text_Create(Panel_att_item_9, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att_item_10 = GUI:Layout_Create(ScrollView_att, "Panel_att_item_10", 0, 0, 142, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_item_10, 255)
GUI:Layout_setBackGroundImage(Panel_att_item_10, "")
GUI:setTag(Panel_att_item_10, 10)

Text_z = GUI:Text_Create(Panel_att_item_10, "Text_z", 2, 13, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 305)

Image_att = GUI:Image_Create(Panel_att_item_10, "Image_att", 41, 13, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 93, 20)
GUI:setTag(Image_att, 294)

Text_bas = GUI:Text_Create(Panel_att_item_10, "Text_bas", 84, 13, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_bas, "#000000", 0)
GUI:setAnchorPoint(Text_bas, 0.5, 0.5)
GUI:setContentSize(Text_bas, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_bas, true)
GUI:setTag(Text_bas, 376)

local Panel_att = GUI:Layout_Create(Panel_1, "Panel_att", 20, 112, 375, 63, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att, 255)
GUI:Layout_setBackGroundImage(Panel_att, "")
GUI:setTag(Panel_att, 190)
GUI:setTouchEnabled(Panel_att, true)

local pl_item_6 = GUI:Layout_Create(Panel_att, "pl_item_6", 254, 2, 122, 30, false)
GUI:Layout_setBackGroundColorOpacity(pl_item_6, 255)
GUI:Layout_setBackGroundImage(pl_item_6, "")
GUI:setTag(pl_item_6, 245)

Image_att = GUI:Image_Create(pl_item_6, "Image_att", 0, 10, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/zbg_1.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 122, 27)
GUI:setTag(Image_att, 246)
GUI:setTouchEnabled(Image_att, true)

Text_z = GUI:Text_Create(pl_item_6, "Text_z", 4, 11, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 247)

local Text_att = GUI:Text_Create(pl_item_6, "Text_att", 57, 10, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_att, "#000000", 0)
GUI:setAnchorPoint(Text_att, 0, 0.5)
GUI:setContentSize(Text_att, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_att, true)
GUI:setTag(Text_att, 248)

local pl_item_5 = GUI:Layout_Create(Panel_att, "pl_item_5", 128, 2, 122, 30, false)
GUI:Layout_setBackGroundColorOpacity(pl_item_5, 255)
GUI:Layout_setBackGroundImage(pl_item_5, "")
GUI:setTag(pl_item_5, 241)

Image_att = GUI:Image_Create(pl_item_5, "Image_att", 0, 10, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/zbg_1.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 122, 27)
GUI:setTag(Image_att, 242)
GUI:setTouchEnabled(Image_att, true)

Text_z = GUI:Text_Create(pl_item_5, "Text_z", 4, 11, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 243)

Text_att = GUI:Text_Create(pl_item_5, "Text_att", 57, 10, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_att, "#000000", 0)
GUI:setAnchorPoint(Text_att, 0, 0.5)
GUI:setContentSize(Text_att, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_att, true)
GUI:setTag(Text_att, 244)

local pl_item_4 = GUI:Layout_Create(Panel_att, "pl_item_4", 2, 2, 122, 30, false)
GUI:Layout_setBackGroundColorOpacity(pl_item_4, 255)
GUI:Layout_setBackGroundImage(pl_item_4, "")
GUI:setTag(pl_item_4, 237)

Image_att = GUI:Image_Create(pl_item_4, "Image_att", -1, 10, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/zbg_1.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 122, 27)
GUI:setTag(Image_att, 238)
GUI:setTouchEnabled(Image_att, true)

Text_z = GUI:Text_Create(pl_item_4, "Text_z", 3, 11, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 239)

Text_att = GUI:Text_Create(pl_item_4, "Text_att", 57, 10, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_att, "#000000", 0)
GUI:setAnchorPoint(Text_att, 0, 0.5)
GUI:setContentSize(Text_att, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_att, true)
GUI:setTag(Text_att, 240)

local pl_item_3 = GUI:Layout_Create(Panel_att, "pl_item_3", 254, 35, 122, 30, false)
GUI:Layout_setBackGroundColorOpacity(pl_item_3, 255)
GUI:Layout_setBackGroundImage(pl_item_3, "")
GUI:setTag(pl_item_3, 233)
GUI:setVisible(pl_item_3, false)

Image_att = GUI:Image_Create(pl_item_3, "Image_att", 0, 14, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/zbg_1.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 122, 27)
GUI:setTag(Image_att, 234)
GUI:setTouchEnabled(Image_att, true)

Text_z = GUI:Text_Create(pl_item_3, "Text_z", 4, 15, 16, "#C8E1FA", "")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 235)

Text_att = GUI:Text_Create(pl_item_3, "Text_att", 37, 15, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att, "#000000", 0)
GUI:setAnchorPoint(Text_att, 0, 0.5)
GUI:setContentSize(Text_att, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att, true)
GUI:setTag(Text_att, 236)

local pl_item_2 = GUI:Layout_Create(Panel_att, "pl_item_2", 128, 35, 122, 30, false)
GUI:Layout_setBackGroundColorOpacity(pl_item_2, 255)
GUI:Layout_setBackGroundImage(pl_item_2, "")
GUI:setTag(pl_item_2, 229)

Image_att = GUI:Image_Create(pl_item_2, "Image_att", 0, 9, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/zbg_1.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 122, 27)
GUI:setTag(Image_att, 230)
GUI:setTouchEnabled(Image_att, true)

Text_z = GUI:Text_Create(pl_item_2, "Text_z", 4, 10, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 231)

Text_att = GUI:Text_Create(pl_item_2, "Text_att", 57, 9, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_att, "#000000", 0)
GUI:setAnchorPoint(Text_att, 0, 0.5)
GUI:setContentSize(Text_att, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_att, true)
GUI:setTag(Text_att, 232)

local pl_item_1 = GUI:Layout_Create(Panel_att, "pl_item_1", 1, 35, 122, 30, false)
GUI:Layout_setBackGroundColorOpacity(pl_item_1, 255)
GUI:Layout_setBackGroundImage(pl_item_1, "")
GUI:setTag(pl_item_1, 225)

Image_att = GUI:Image_Create(pl_item_1, "Image_att", 0, 9, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/zbg_1.png")
GUI:setAnchorPoint(Image_att, 0, 0.5)
GUI:setContentSize(Image_att, 122, 27)
GUI:setTag(Image_att, 226)
GUI:setTouchEnabled(Image_att, true)

Text_z = GUI:Text_Create(pl_item_1, "Text_z", 5, 10, 16, "#C8E1FA", "--")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 12, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 227)

Text_att = GUI:Text_Create(pl_item_1, "Text_att", 57, 9, 14, "#FFFFFF", "00")
GUI:Text_enableOutline(Text_att, "#000000", 0)
GUI:setAnchorPoint(Text_att, 0, 0.5)
GUI:setContentSize(Text_att, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_att, true)
GUI:setTag(Text_att, 228)

local Button_attr = GUI:Button_Create(Panel_att, "Button_attr", 254, 31, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_attr.png")
GUI:Button_setTitleFontSize(Button_attr, 10)
GUI:Button_setTitleText(Button_attr, "")
GUI:setContentSize(Button_attr, 122, 28)

local Panel_att_ele_title = GUI:Layout_Create(Panel_1, "Panel_att_ele_title", 18, 83, 384, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_ele_title, 255)
GUI:Layout_setBackGroundImage(Panel_att_ele_title, "")
GUI:setTag(Panel_att_ele_title, 252)

Image_att = GUI:Image_Create(Panel_att_ele_title, "Image_att", 2, 24, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_total.png")
GUI:setAnchorPoint(Image_att, 0, 1)
GUI:setContentSize(Image_att, 64, 16)
GUI:setTag(Image_att, 433)

local btn_show_1 = GUI:Button_Create(Panel_att_ele_title, "btn_show_1", 81, 14, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_1.png")
GUI:Button_setTitleFontSize(btn_show_1, 10)
GUI:Button_setTitleText(btn_show_1, "")
GUI:setAnchorPoint(btn_show_1, 0.5, 0.5)
GUI:setContentSize(btn_show_1, 24, 26)
GUI:setTag(btn_show_1, 388)
GUI:setTouchEnabled(btn_show_1, false)

local btn_show_2 = GUI:Button_Create(Panel_att_ele_title, "btn_show_2", 125, 14, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_2.png")
GUI:Button_setTitleFontSize(btn_show_2, 10)
GUI:Button_setTitleText(btn_show_2, "")
GUI:setAnchorPoint(btn_show_2, 0.5, 0.5)
GUI:setContentSize(btn_show_2, 26, 26)
GUI:setTag(btn_show_2, 389)
GUI:setTouchEnabled(btn_show_2, false)

local btn_show_3 = GUI:Button_Create(Panel_att_ele_title, "btn_show_3", 168, 14, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_3.png")
GUI:Button_setTitleFontSize(btn_show_3, 10)
GUI:Button_setTitleText(btn_show_3, "")
GUI:setAnchorPoint(btn_show_3, 0.5, 0.5)
GUI:setContentSize(btn_show_3, 24, 26)
GUI:setTag(btn_show_3, 390)
GUI:setTouchEnabled(btn_show_3, false)

local btn_show_4 = GUI:Button_Create(Panel_att_ele_title, "btn_show_4", 213, 14, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_4.png")
GUI:Button_setTitleFontSize(btn_show_4, 10)
GUI:Button_setTitleText(btn_show_4, "")
GUI:setAnchorPoint(btn_show_4, 0.5, 0.5)
GUI:setContentSize(btn_show_4, 26, 24)
GUI:setTag(btn_show_4, 391)
GUI:setTouchEnabled(btn_show_4, false)

local btn_show_5 = GUI:Button_Create(Panel_att_ele_title, "btn_show_5", 258, 14, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_5.png")
GUI:Button_setTitleFontSize(btn_show_5, 10)
GUI:Button_setTitleText(btn_show_5, "")
GUI:setAnchorPoint(btn_show_5, 0.5, 0.5)
GUI:setContentSize(btn_show_5, 42, 26)
GUI:setTag(btn_show_5, 392)
GUI:setTouchEnabled(btn_show_5, false)

local btn_show_6 = GUI:Button_Create(Panel_att_ele_title, "btn_show_6", 302, 14, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_6.png")
GUI:Button_setTitleFontSize(btn_show_6, 10)
GUI:Button_setTitleText(btn_show_6, "")
GUI:setAnchorPoint(btn_show_6, 0.5, 0.5)
GUI:setContentSize(btn_show_6, 40, 26)
GUI:setTag(btn_show_6, 393)
GUI:setTouchEnabled(btn_show_6, false)

local btn_show_7 = GUI:Button_Create(Panel_att_ele_title, "btn_show_7", 347, 14, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_7.png")
GUI:Button_setTitleFontSize(btn_show_7, 10)
GUI:Button_setTitleText(btn_show_7, "")
GUI:setAnchorPoint(btn_show_7, 0.5, 0.5)
GUI:setContentSize(btn_show_7, 40, 26)
GUI:setTag(btn_show_7, 394)
GUI:setTouchEnabled(btn_show_7, false)

local Panel_att_ele_1 = GUI:Layout_Create(Panel_1, "Panel_att_ele_1", 18, 59, 384, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_ele_1, 255)
GUI:Layout_setBackGroundImage(Panel_att_ele_1, "")
GUI:setTag(Panel_att_ele_1, 252)

Image_att = GUI:Image_Create(Panel_att_ele_1, "Image_att", 0, 24, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_t_bg.png")
GUI:setAnchorPoint(Image_att, 0, 1)
GUI:setContentSize(Image_att, 68, 20)
GUI:setTag(Image_att, 433)

local Image_att_1 = GUI:Image_Create(Panel_att_ele_1, "Image_att_1", 2, 26, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_t_1.png")
GUI:setAnchorPoint(Image_att_1, 0, 1)
GUI:setContentSize(Image_att_1, 64, 16)
GUI:setTag(Image_att_1, 433)

Text_z = GUI:Text_Create(Panel_att_ele_1, "Text_z", 3, 14, 16, "#FB9700", "攻击元素")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 64, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 321)
GUI:setVisible(Text_z, false)

btn_show_1 = GUI:Button_Create(Panel_att_ele_1, "btn_show_1", 79, 19, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_1.png")
GUI:Button_loadTextureDisabled(btn_show_1, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_ys_1.png")
GUI:Button_loadTexturePressed(btn_show_1, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_1.png")
GUI:Button_setTitleFontSize(btn_show_1, 10)
GUI:Button_setTitleText(btn_show_1, "")
GUI:setAnchorPoint(btn_show_1, 0.5, 0.5)
GUI:setContentSize(btn_show_1, 20, 20)
GUI:setTag(btn_show_1, 388)
GUI:setTouchEnabled(btn_show_1, false)

btn_show_2 = GUI:Button_Create(Panel_att_ele_1, "btn_show_2", 123, 19, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_2.png")
GUI:Button_loadTextureDisabled(btn_show_2, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_ys_2.png")
GUI:Button_loadTexturePressed(btn_show_2, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_2.png")
GUI:Button_setTitleFontSize(btn_show_2, 10)
GUI:Button_setTitleText(btn_show_2, "")
GUI:setAnchorPoint(btn_show_2, 0.5, 0.5)
GUI:setContentSize(btn_show_2, 20, 20)
GUI:setTag(btn_show_2, 389)
GUI:setTouchEnabled(btn_show_2, false)

btn_show_3 = GUI:Button_Create(Panel_att_ele_1, "btn_show_3", 167, 19, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_3.png")
GUI:Button_loadTextureDisabled(btn_show_3, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_ys_3.png")
GUI:Button_loadTexturePressed(btn_show_3, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_3.png")
GUI:Button_setTitleFontSize(btn_show_3, 10)
GUI:Button_setTitleText(btn_show_3, "")
GUI:setAnchorPoint(btn_show_3, 0.5, 0.5)
GUI:setContentSize(btn_show_3, 20, 20)
GUI:setTag(btn_show_3, 390)
GUI:setTouchEnabled(btn_show_3, false)

btn_show_4 = GUI:Button_Create(Panel_att_ele_1, "btn_show_4", 212, 19, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_4.png")
GUI:Button_loadTextureDisabled(btn_show_4, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_ys_4.png")
GUI:Button_loadTexturePressed(btn_show_4, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_4.png")
GUI:Button_setTitleFontSize(btn_show_4, 10)
GUI:Button_setTitleText(btn_show_4, "")
GUI:setAnchorPoint(btn_show_4, 0.5, 0.5)
GUI:setContentSize(btn_show_4, 20, 20)
GUI:setTag(btn_show_4, 391)
GUI:setTouchEnabled(btn_show_4, false)

btn_show_5 = GUI:Button_Create(Panel_att_ele_1, "btn_show_5", 256, 19, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_5.png")
GUI:Button_loadTextureDisabled(btn_show_5, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_ys_5.png")
GUI:Button_loadTexturePressed(btn_show_5, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_5.png")
GUI:Button_setTitleFontSize(btn_show_5, 10)
GUI:Button_setTitleText(btn_show_5, "")
GUI:setAnchorPoint(btn_show_5, 0.5, 0.5)
GUI:setContentSize(btn_show_5, 20, 20)
GUI:setTag(btn_show_5, 392)
GUI:setTouchEnabled(btn_show_5, false)

btn_show_6 = GUI:Button_Create(Panel_att_ele_1, "btn_show_6", 300, 19, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_6.png")
GUI:Button_loadTextureDisabled(btn_show_6, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_ys_6.png")
GUI:Button_loadTexturePressed(btn_show_6, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_6.png")
GUI:Button_setTitleFontSize(btn_show_6, 10)
GUI:Button_setTitleText(btn_show_6, "")
GUI:setAnchorPoint(btn_show_6, 0.5, 0.5)
GUI:setContentSize(btn_show_6, 20, 20)
GUI:setTag(btn_show_6, 393)
GUI:setTouchEnabled(btn_show_6, false)

btn_show_7 = GUI:Button_Create(Panel_att_ele_1, "btn_show_7", 345, 20, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_7.png")
GUI:Button_loadTextureDisabled(btn_show_7, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_ys_7.png")
GUI:Button_loadTexturePressed(btn_show_7, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_7.png")
GUI:Button_setTitleFontSize(btn_show_7, 10)
GUI:Button_setTitleText(btn_show_7, "")
GUI:setAnchorPoint(btn_show_7, 0.5, 0.5)
GUI:setContentSize(btn_show_7, 20, 20)
GUI:setTag(btn_show_7, 394)
GUI:setTouchEnabled(btn_show_7, false)

local Text_att_1 = GUI:Text_Create(Panel_att_ele_1, "Text_att_1", 88, 19, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_1, "#000000", 0)
GUI:setAnchorPoint(Text_att_1, 0, 0.5)
GUI:setContentSize(Text_att_1, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_1, true)
GUI:setTag(Text_att_1, 396)

local Text_att_2 = GUI:Text_Create(Panel_att_ele_1, "Text_att_2", 134, 18, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_2, "#000000", 0)
GUI:setAnchorPoint(Text_att_2, 0, 0.5)
GUI:setContentSize(Text_att_2, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_2, true)
GUI:setTag(Text_att_2, 397)

local Text_att_3 = GUI:Text_Create(Panel_att_ele_1, "Text_att_3", 178, 19, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_3, "#000000", 0)
GUI:setAnchorPoint(Text_att_3, 0, 0.5)
GUI:setContentSize(Text_att_3, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_3, true)
GUI:setTag(Text_att_3, 398)

local Text_att_4 = GUI:Text_Create(Panel_att_ele_1, "Text_att_4", 223, 19, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_4, "#000000", 0)
GUI:setAnchorPoint(Text_att_4, 0, 0.5)
GUI:setContentSize(Text_att_4, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_4, true)
GUI:setTag(Text_att_4, 399)

local Text_att_5 = GUI:Text_Create(Panel_att_ele_1, "Text_att_5", 267, 19, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_5, "#000000", 0)
GUI:setAnchorPoint(Text_att_5, 0, 0.5)
GUI:setContentSize(Text_att_5, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_5, true)
GUI:setTag(Text_att_5, 400)

local Text_att_6 = GUI:Text_Create(Panel_att_ele_1, "Text_att_6", 312, 19, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_6, "#000000", 0)
GUI:setAnchorPoint(Text_att_6, 0, 0.5)
GUI:setContentSize(Text_att_6, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_6, true)
GUI:setTag(Text_att_6, 401)

local Text_att_7 = GUI:Text_Create(Panel_att_ele_1, "Text_att_7", 356, 20, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_7, "#000000", 0)
GUI:setAnchorPoint(Text_att_7, 0, 0.5)
GUI:setContentSize(Text_att_7, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_7, true)
GUI:setTag(Text_att_7, 402)

local Panel_att_ele_2 = GUI:Layout_Create(Panel_1, "Panel_att_ele_2", 18, 35, 384, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_ele_2, 255)
GUI:Layout_setBackGroundImage(Panel_att_ele_2, "")
GUI:setTag(Panel_att_ele_2, 253)

Image_att = GUI:Image_Create(Panel_att_ele_2, "Image_att", 0, 24, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_t_bg.png")
GUI:setAnchorPoint(Image_att, 0, 1)
GUI:setContentSize(Image_att, 68, 20)
GUI:setTag(Image_att, 434)

Image_att_1 = GUI:Image_Create(Panel_att_ele_2, "Image_att_1", 4, 25, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_t_2.png")
GUI:setAnchorPoint(Image_att_1, 0, 1)
GUI:setContentSize(Image_att_1, 56, 16)
GUI:setTag(Image_att_1, 433)

Text_z = GUI:Text_Create(Panel_att_ele_2, "Text_z", 3, 15, 16, "#01E800", "强  元  素")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 64, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 322)
GUI:setVisible(Text_z, false)

btn_show_1 = GUI:Button_Create(Panel_att_ele_2, "btn_show_1", 79, 18, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_1.png")
GUI:Button_loadTextureDisabled(btn_show_1, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_1.png")
GUI:Button_loadTexturePressed(btn_show_1, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_1.png")
GUI:Button_setTitleFontSize(btn_show_1, 10)
GUI:Button_setTitleText(btn_show_1, "")
GUI:setAnchorPoint(btn_show_1, 0.5, 0.5)
GUI:setContentSize(btn_show_1, 20, 20)
GUI:setTag(btn_show_1, 404)
GUI:setTouchEnabled(btn_show_1, false)

btn_show_2 = GUI:Button_Create(Panel_att_ele_2, "btn_show_2", 123, 18, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_2.png")
GUI:Button_loadTextureDisabled(btn_show_2, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_2.png")
GUI:Button_loadTexturePressed(btn_show_2, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_2.png")
GUI:Button_setTitleFontSize(btn_show_2, 10)
GUI:Button_setTitleText(btn_show_2, "")
GUI:setAnchorPoint(btn_show_2, 0.5, 0.5)
GUI:setContentSize(btn_show_2, 20, 20)
GUI:setTag(btn_show_2, 405)
GUI:setTouchEnabled(btn_show_2, false)

btn_show_3 = GUI:Button_Create(Panel_att_ele_2, "btn_show_3", 167, 18, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_3.png")
GUI:Button_loadTextureDisabled(btn_show_3, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_3.png")
GUI:Button_loadTexturePressed(btn_show_3, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_3.png")
GUI:Button_setTitleFontSize(btn_show_3, 10)
GUI:Button_setTitleText(btn_show_3, "")
GUI:setAnchorPoint(btn_show_3, 0.5, 0.5)
GUI:setContentSize(btn_show_3, 20, 20)
GUI:setTag(btn_show_3, 406)
GUI:setTouchEnabled(btn_show_3, false)

btn_show_4 = GUI:Button_Create(Panel_att_ele_2, "btn_show_4", 212, 18, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_4.png")
GUI:Button_loadTextureDisabled(btn_show_4, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_4.png")
GUI:Button_loadTexturePressed(btn_show_4, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_4.png")
GUI:Button_setTitleFontSize(btn_show_4, 10)
GUI:Button_setTitleText(btn_show_4, "")
GUI:setAnchorPoint(btn_show_4, 0.5, 0.5)
GUI:setContentSize(btn_show_4, 20, 20)
GUI:setTag(btn_show_4, 407)
GUI:setTouchEnabled(btn_show_4, false)

btn_show_5 = GUI:Button_Create(Panel_att_ele_2, "btn_show_5", 256, 18, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_5.png")
GUI:Button_loadTextureDisabled(btn_show_5, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_5.png")
GUI:Button_loadTexturePressed(btn_show_5, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_5.png")
GUI:Button_setTitleFontSize(btn_show_5, 10)
GUI:Button_setTitleText(btn_show_5, "")
GUI:setAnchorPoint(btn_show_5, 0.5, 0.5)
GUI:setContentSize(btn_show_5, 20, 20)
GUI:setTag(btn_show_5, 408)
GUI:setTouchEnabled(btn_show_5, false)

btn_show_6 = GUI:Button_Create(Panel_att_ele_2, "btn_show_6", 300, 18, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_6.png")
GUI:Button_loadTextureDisabled(btn_show_6, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_6.png")
GUI:Button_loadTexturePressed(btn_show_6, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_6.png")
GUI:Button_setTitleFontSize(btn_show_6, 10)
GUI:Button_setTitleText(btn_show_6, "")
GUI:setAnchorPoint(btn_show_6, 0.5, 0.5)
GUI:setContentSize(btn_show_6, 20, 20)
GUI:setTag(btn_show_6, 409)
GUI:setTouchEnabled(btn_show_6, false)

btn_show_7 = GUI:Button_Create(Panel_att_ele_2, "btn_show_7", 345, 18, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_7.png")
GUI:Button_loadTextureDisabled(btn_show_7, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_7.png")
GUI:Button_loadTexturePressed(btn_show_7, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_7.png")
GUI:Button_setTitleFontSize(btn_show_7, 10)
GUI:Button_setTitleText(btn_show_7, "")
GUI:setAnchorPoint(btn_show_7, 0.5, 0.5)
GUI:setContentSize(btn_show_7, 20, 20)
GUI:setTag(btn_show_7, 410)
GUI:setTouchEnabled(btn_show_7, false)

Text_att_1 = GUI:Text_Create(Panel_att_ele_2, "Text_att_1", 89, 18, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_1, "#000000", 0)
GUI:setAnchorPoint(Text_att_1, 0, 0.5)
GUI:setContentSize(Text_att_1, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_1, true)
GUI:setTag(Text_att_1, 411)

Text_att_2 = GUI:Text_Create(Panel_att_ele_2, "Text_att_2", 132, 18, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_2, "#000000", 0)
GUI:setAnchorPoint(Text_att_2, 0, 0.5)
GUI:setContentSize(Text_att_2, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_2, true)
GUI:setTag(Text_att_2, 412)

Text_att_3 = GUI:Text_Create(Panel_att_ele_2, "Text_att_3", 177, 18, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_3, "#000000", 0)
GUI:setAnchorPoint(Text_att_3, 0, 0.5)
GUI:setContentSize(Text_att_3, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_3, true)
GUI:setTag(Text_att_3, 413)

Text_att_4 = GUI:Text_Create(Panel_att_ele_2, "Text_att_4", 222, 18, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_4, "#000000", 0)
GUI:setAnchorPoint(Text_att_4, 0, 0.5)
GUI:setContentSize(Text_att_4, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_4, true)
GUI:setTag(Text_att_4, 414)

Text_att_5 = GUI:Text_Create(Panel_att_ele_2, "Text_att_5", 266, 18, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_5, "#000000", 0)
GUI:setAnchorPoint(Text_att_5, 0, 0.5)
GUI:setContentSize(Text_att_5, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_5, true)
GUI:setTag(Text_att_5, 415)

Text_att_6 = GUI:Text_Create(Panel_att_ele_2, "Text_att_6", 309, 18, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_6, "#000000", 0)
GUI:setAnchorPoint(Text_att_6, 0, 0.5)
GUI:setContentSize(Text_att_6, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_6, true)
GUI:setTag(Text_att_6, 416)

Text_att_7 = GUI:Text_Create(Panel_att_ele_2, "Text_att_7", 355, 18, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_7, "#000000", 0)
GUI:setAnchorPoint(Text_att_7, 0, 0.5)
GUI:setContentSize(Text_att_7, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_7, true)
GUI:setTag(Text_att_7, 417)

local Panel_att_ele_3 = GUI:Layout_Create(Panel_1, "Panel_att_ele_3", 18, 11, 384, 27, false)
GUI:Layout_setBackGroundColorOpacity(Panel_att_ele_3, 255)
GUI:Layout_setBackGroundImage(Panel_att_ele_3, "")
GUI:setTag(Panel_att_ele_3, 254)

Image_att = GUI:Image_Create(Panel_att_ele_3, "Image_att", 0, 24, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/title_t_bg.png")
GUI:setAnchorPoint(Image_att, 0, 1)
GUI:setContentSize(Image_att, 68, 20)
GUI:setTag(Image_att, 435)

Image_att_1 = GUI:Image_Create(Panel_att_ele_3, "Image_att_1", 4, 24, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/total_t_3.png")
GUI:setAnchorPoint(Image_att_1, 0, 1)
GUI:setContentSize(Image_att_1, 56, 16)
GUI:setTag(Image_att_1, 433)

Text_z = GUI:Text_Create(Panel_att_ele_3, "Text_z", 3, 14, 16, "#2FB9B8", "弱  元  素")
GUI:Text_enableOutline(Text_z, "#000000", 0)
GUI:setAnchorPoint(Text_z, 0, 0.5)
GUI:setContentSize(Text_z, 64, 18)
GUI:setIgnoreContentAdaptWithSize(Text_z, true)
GUI:setTag(Text_z, 323)
GUI:setVisible(Text_z, false)

btn_show_1 = GUI:Button_Create(Panel_att_ele_3, "btn_show_1", 79, 16, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_1.png")
GUI:Button_loadTextureDisabled(btn_show_1, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_1.png")
GUI:Button_loadTexturePressed(btn_show_1, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_1.png")
GUI:Button_setTitleFontSize(btn_show_1, 10)
GUI:Button_setTitleText(btn_show_1, "")
GUI:setAnchorPoint(btn_show_1, 0.5, 0.5)
GUI:setContentSize(btn_show_1, 20, 20)
GUI:setTag(btn_show_1, 419)
GUI:setTouchEnabled(btn_show_1, false)

btn_show_2 = GUI:Button_Create(Panel_att_ele_3, "btn_show_2", 123, 16, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_2.png")
GUI:Button_loadTextureDisabled(btn_show_2, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_2.png")
GUI:Button_loadTexturePressed(btn_show_2, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_2.png")
GUI:Button_setTitleFontSize(btn_show_2, 10)
GUI:Button_setTitleText(btn_show_2, "")
GUI:setAnchorPoint(btn_show_2, 0.5, 0.5)
GUI:setContentSize(btn_show_2, 20, 20)
GUI:setTag(btn_show_2, 420)
GUI:setTouchEnabled(btn_show_2, false)

btn_show_3 = GUI:Button_Create(Panel_att_ele_3, "btn_show_3", 167, 16, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_3.png")
GUI:Button_loadTextureDisabled(btn_show_3, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_3.png")
GUI:Button_loadTexturePressed(btn_show_3, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_3.png")
GUI:Button_setTitleFontSize(btn_show_3, 10)
GUI:Button_setTitleText(btn_show_3, "")
GUI:setAnchorPoint(btn_show_3, 0.5, 0.5)
GUI:setContentSize(btn_show_3, 20, 20)
GUI:setTag(btn_show_3, 421)
GUI:setTouchEnabled(btn_show_3, false)

btn_show_4 = GUI:Button_Create(Panel_att_ele_3, "btn_show_4", 212, 16, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_4.png")
GUI:Button_loadTextureDisabled(btn_show_4, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_4.png")
GUI:Button_loadTexturePressed(btn_show_4, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_4.png")
GUI:Button_setTitleFontSize(btn_show_4, 10)
GUI:Button_setTitleText(btn_show_4, "")
GUI:setAnchorPoint(btn_show_4, 0.5, 0.5)
GUI:setContentSize(btn_show_4, 20, 20)
GUI:setTag(btn_show_4, 422)
GUI:setTouchEnabled(btn_show_4, false)

btn_show_5 = GUI:Button_Create(Panel_att_ele_3, "btn_show_5", 256, 16, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_5.png")
GUI:Button_loadTextureDisabled(btn_show_5, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_5.png")
GUI:Button_loadTexturePressed(btn_show_5, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_5.png")
GUI:Button_setTitleFontSize(btn_show_5, 10)
GUI:Button_setTitleText(btn_show_5, "")
GUI:setAnchorPoint(btn_show_5, 0.5, 0.5)
GUI:setContentSize(btn_show_5, 20, 20)
GUI:setTag(btn_show_5, 423)
GUI:setTouchEnabled(btn_show_5, false)

btn_show_6 = GUI:Button_Create(Panel_att_ele_3, "btn_show_6", 300, 16, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_6.png")
GUI:Button_loadTextureDisabled(btn_show_6, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_6.png")
GUI:Button_loadTexturePressed(btn_show_6, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_6.png")
GUI:Button_setTitleFontSize(btn_show_6, 10)
GUI:Button_setTitleText(btn_show_6, "")
GUI:setAnchorPoint(btn_show_6, 0.5, 0.5)
GUI:setContentSize(btn_show_6, 20, 20)
GUI:setTag(btn_show_6, 424)
GUI:setTouchEnabled(btn_show_6, false)

btn_show_7 = GUI:Button_Create(Panel_att_ele_3, "btn_show_7", 345, 16, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_7.png")
GUI:Button_loadTextureDisabled(btn_show_7, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_l_7.png")
GUI:Button_loadTexturePressed(btn_show_7, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_a_7.png")
GUI:Button_setTitleFontSize(btn_show_7, 10)
GUI:Button_setTitleText(btn_show_7, "")
GUI:setAnchorPoint(btn_show_7, 0.5, 0.5)
GUI:setContentSize(btn_show_7, 20, 20)
GUI:setTag(btn_show_7, 425)
GUI:setTouchEnabled(btn_show_7, false)

Text_att_1 = GUI:Text_Create(Panel_att_ele_3, "Text_att_1", 89, 16, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_1, "#000000", 0)
GUI:setAnchorPoint(Text_att_1, 0, 0.5)
GUI:setContentSize(Text_att_1, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_1, true)
GUI:setTag(Text_att_1, 426)

Text_att_2 = GUI:Text_Create(Panel_att_ele_3, "Text_att_2", 133, 16, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_2, "#000000", 0)
GUI:setAnchorPoint(Text_att_2, 0, 0.5)
GUI:setContentSize(Text_att_2, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_2, true)
GUI:setTag(Text_att_2, 427)

Text_att_3 = GUI:Text_Create(Panel_att_ele_3, "Text_att_3", 176, 16, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_3, "#000000", 0)
GUI:setAnchorPoint(Text_att_3, 0, 0.5)
GUI:setContentSize(Text_att_3, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_3, true)
GUI:setTag(Text_att_3, 428)

Text_att_4 = GUI:Text_Create(Panel_att_ele_3, "Text_att_4", 221, 16, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_4, "#000000", 0)
GUI:setAnchorPoint(Text_att_4, 0, 0.5)
GUI:setContentSize(Text_att_4, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_4, true)
GUI:setTag(Text_att_4, 429)

Text_att_5 = GUI:Text_Create(Panel_att_ele_3, "Text_att_5", 265, 16, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_5, "#000000", 0)
GUI:setAnchorPoint(Text_att_5, 0, 0.5)
GUI:setContentSize(Text_att_5, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_5, true)
GUI:setTag(Text_att_5, 430)

Text_att_6 = GUI:Text_Create(Panel_att_ele_3, "Text_att_6", 310, 17, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_6, "#000000", 0)
GUI:setAnchorPoint(Text_att_6, 0, 0.5)
GUI:setContentSize(Text_att_6, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_6, true)
GUI:setTag(Text_att_6, 431)

Text_att_7 = GUI:Text_Create(Panel_att_ele_3, "Text_att_7", 355, 16, 14, "#FFFFFF", "")
GUI:Text_enableOutline(Text_att_7, "#000000", 0)
GUI:setAnchorPoint(Text_att_7, 0, 0.5)
GUI:setContentSize(Text_att_7, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_att_7, true)
GUI:setTag(Text_att_7, 432)

local Text_name = GUI:Text_Create(Panel_1, "Text_name", 175, 584, 18, "#FFE400", "名字")
GUI:Text_enableOutline(Text_name, "#000000", 0)
GUI:setAnchorPoint(Text_name, 0.5, 1)
GUI:setContentSize(Text_name, 36, 20)
GUI:setIgnoreContentAdaptWithSize(Text_name, true)
GUI:setTag(Text_name, 442)

local Text_guild = GUI:Text_Create(Panel_1, "Text_guild", 175, 561, 18, "#FFE400", "")
GUI:Text_enableOutline(Text_guild, "#000000", 0)
GUI:setAnchorPoint(Text_guild, 0.5, 1)
GUI:setContentSize(Text_guild, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_guild, true)
GUI:setTag(Text_guild, 251)

local Text_leader = GUI:Text_Create(Panel_1, "Text_leader", 175, 539, 18, "#FFE400", "")
GUI:Text_enableOutline(Text_leader, "#000000", 0)
GUI:setAnchorPoint(Text_leader, 0.5, 1)
GUI:setContentSize(Text_leader, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_leader, true)
GUI:setTag(Text_leader, 250)

local Node_other = GUI:Node_Create(Panel_1, "Node_other", -24, 501)
GUI:setTag(Node_other, 327)

local Image_dear_head = GUI:Image_Create(Node_other, "Image_dear_head", 136, 12, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:Image_setScale9Enabled(Image_dear_head, true)
GUI:Image_setScale9Slice(Image_dear_head, 10, 10, 10, 9)
GUI:setAnchorPoint(Image_dear_head, 0, 1)
GUI:setContentSize(Image_dear_head, 20, 20)
GUI:setTag(Image_dear_head, 328)

local Image_dear_icon = GUI:Image_Create(Node_other, "Image_dear_icon", 148, 0, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/19001298.png")
GUI:setAnchorPoint(Image_dear_icon, 0.5, 0.5)
GUI:setContentSize(Image_dear_icon, 16, 12)
GUI:setTag(Image_dear_icon, 702)

local Image_dear_bgname = GUI:Image_Create(Node_other, "Image_dear_bgname", 266, 12, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:Image_setScale9Enabled(Image_dear_bgname, true)
GUI:Image_setScale9Slice(Image_dear_bgname, 10, 10, 10, 9)
GUI:setAnchorPoint(Image_dear_bgname, 1, 1)
GUI:setContentSize(Image_dear_bgname, 105, 20)
GUI:setTag(Image_dear_bgname, 326)

local Text_dear_name = GUI:Text_Create(Node_other, "Text_dear_name", 164, 2, 16, "#FF00FF", "")
GUI:Text_enableOutline(Text_dear_name, "#000000", 0)
GUI:setAnchorPoint(Text_dear_name, 0, 0.5)
GUI:setContentSize(Text_dear_name, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_dear_name, true)
GUI:setTag(Text_dear_name, 329)

local Node_sifu = GUI:Node_Create(Panel_1, "Node_sifu", -24, 480)
GUI:setTag(Node_sifu, 827)

local Image_sifu_head = GUI:Image_Create(Node_sifu, "Image_sifu_head", 136, 12, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:Image_setScale9Enabled(Image_sifu_head, true)
GUI:Image_setScale9Slice(Image_sifu_head, 10, 10, 10, 9)
GUI:setAnchorPoint(Image_sifu_head, 0, 1)
GUI:setContentSize(Image_sifu_head, 20, 20)
GUI:setTag(Image_sifu_head, 828)

local Image_sifu_icon = GUI:Image_Create(Node_sifu, "Image_sifu_icon", 148, 0, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/19001297.png")
GUI:setAnchorPoint(Image_sifu_icon, 0.5, 0.5)
GUI:setContentSize(Image_sifu_icon, 16, 12)
GUI:setTag(Image_sifu_icon, 829)

local Image_sifu_bgname = GUI:Image_Create(Node_sifu, "Image_sifu_bgname", 266, 12, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/bg_2.png")
GUI:Image_setScale9Enabled(Image_sifu_bgname, true)
GUI:Image_setScale9Slice(Image_sifu_bgname, 10, 10, 10, 9)
GUI:setAnchorPoint(Image_sifu_bgname, 1, 1)
GUI:setContentSize(Image_sifu_bgname, 105, 20)
GUI:setTag(Image_sifu_bgname, 830)

local Text_sifu_name = GUI:Text_Create(Node_sifu, "Text_sifu_name", 164, 2, 16, "#FF00FF", "")
GUI:Text_enableOutline(Text_sifu_name, "#000000", 0)
GUI:setAnchorPoint(Text_sifu_name, 0, 0.5)
GUI:setContentSize(Text_sifu_name, 0, 0)
GUI:setIgnoreContentAdaptWithSize(Text_sifu_name, true)
GUI:setTag(Text_sifu_name, 831)

local Panel_pos101 = GUI:Layout_Create(Panel_1, "Panel_pos101", 145, 337, 85, 155, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos101, 255)
GUI:Layout_setBackGroundImage(Panel_pos101, "")
GUI:setAnchorPoint(Panel_pos101, 0.5, 0.5)
GUI:setTag(Panel_pos101, 32)
GUI:setTouchEnabled(Panel_pos101, true)

local Panel_pos102 = GUI:Layout_Create(Panel_1, "Panel_pos102", 58, 421, 88, 140, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos102, 255)
GUI:Layout_setBackGroundImage(Panel_pos102, "")
GUI:setAnchorPoint(Panel_pos102, 0.5, 0.5)
GUI:setTag(Panel_pos102, 31)
GUI:setTouchEnabled(Panel_pos102, true)

local Panel_pos103 = GUI:Layout_Create(Panel_1, "Panel_pos103", 132, 455, 60, 80, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos103, 255)
GUI:Layout_setBackGroundImage(Panel_pos103, "")
GUI:setAnchorPoint(Panel_pos103, 0.5, 0.5)
GUI:setTag(Panel_pos103, 33)
GUI:setTouchEnabled(Panel_pos103, true)

local Panel_pos104 = GUI:Layout_Create(Panel_1, "Panel_pos104", 175, 362, 50, 70, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos104, 255)
GUI:Layout_setBackGroundImage(Panel_pos104, "")
GUI:setAnchorPoint(Panel_pos104, 0.5, 0.5)
GUI:setTag(Panel_pos104, 82)
GUI:setTouchEnabled(Panel_pos104, true)

local Panel_pos1 = GUI:Layout_Create(Panel_1, "Panel_pos1", 41, 391, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos1, 255)
GUI:Layout_setBackGroundImage(Panel_pos1, "")
GUI:setAnchorPoint(Panel_pos1, 0.5, 0.5)
GUI:setTag(Panel_pos1, 176)
GUI:setTouchEnabled(Panel_pos1, true)

local Image_bg = GUI:Image_Create(Panel_pos1, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 177)

local Image_icon = GUI:Image_Create(Panel_pos1, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015043.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 36, 36)
GUI:setTag(Image_icon, 178)

local Node_item = GUI:Node_Create(Panel_pos1, "Node_item", 21, 23)
GUI:setTag(Node_item, 183)

local Panel_pos0 = GUI:Layout_Create(Panel_1, "Panel_pos0", 41, 347, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos0, 255)
GUI:Layout_setBackGroundImage(Panel_pos0, "")
GUI:setAnchorPoint(Panel_pos0, 0.5, 0.5)
GUI:setTag(Panel_pos0, 173)
GUI:setTouchEnabled(Panel_pos0, true)

Image_bg = GUI:Image_Create(Panel_pos0, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 174)

Image_icon = GUI:Image_Create(Panel_pos0, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015045.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 36, 36)
GUI:setTag(Image_icon, 175)

Node_item = GUI:Node_Create(Panel_pos0, "Node_item", 21, 23)
GUI:setTag(Node_item, 184)

local Panel_pos5 = GUI:Layout_Create(Panel_1, "Panel_pos5", 41, 303, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos5, 255)
GUI:Layout_setBackGroundImage(Panel_pos5, "")
GUI:setAnchorPoint(Panel_pos5, 0.5, 0.5)
GUI:setTag(Panel_pos5, 41)
GUI:setTouchEnabled(Panel_pos5, true)

Image_bg = GUI:Image_Create(Panel_pos5, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 46)

Image_icon = GUI:Image_Create(Panel_pos5, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015034.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 75)

Node_item = GUI:Node_Create(Panel_pos5, "Node_item", 21, 23)
GUI:setTag(Node_item, 189)

local Panel_pos7 = GUI:Layout_Create(Panel_1, "Panel_pos7", 41, 259, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos7, 255)
GUI:Layout_setBackGroundImage(Panel_pos7, "")
GUI:setAnchorPoint(Panel_pos7, 0.5, 0.5)
GUI:setTag(Panel_pos7, 40)
GUI:setTouchEnabled(Panel_pos7, true)

Image_bg = GUI:Image_Create(Panel_pos7, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 48)

Image_icon = GUI:Image_Create(Panel_pos7, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015035.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 74)

Node_item = GUI:Node_Create(Panel_pos7, "Node_item", 21, 23)
GUI:setTag(Node_item, 188)

local Panel_pos11 = GUI:Layout_Create(Panel_1, "Panel_pos11", 102, 214, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos11, 255)
GUI:Layout_setBackGroundImage(Panel_pos11, "")
GUI:setAnchorPoint(Panel_pos11, 0.5, 0.5)
GUI:setTag(Panel_pos11, 63)
GUI:setTouchEnabled(Panel_pos11, true)

Image_bg = GUI:Image_Create(Panel_pos11, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 64)

Image_icon = GUI:Image_Create(Panel_pos11, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015037.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 79)

Node_item = GUI:Node_Create(Panel_pos11, "Node_item", 21, 23)
GUI:setTag(Node_item, 195)

local Panel_pos10 = GUI:Layout_Create(Panel_1, "Panel_pos10", 160, 215, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos10, 255)
GUI:Layout_setBackGroundImage(Panel_pos10, "")
GUI:setAnchorPoint(Panel_pos10, 0.5, 0.5)
GUI:setTag(Panel_pos10, 66)
GUI:setTouchEnabled(Panel_pos10, true)

Image_bg = GUI:Image_Create(Panel_pos10, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 67)

Image_icon = GUI:Image_Create(Panel_pos10, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015038.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 30, 15)
GUI:setTag(Image_icon, 80)

Node_item = GUI:Node_Create(Panel_pos10, "Node_item", 21, 23)
GUI:setTag(Node_item, 196)

local Panel_pos9 = GUI:Layout_Create(Panel_1, "Panel_pos9", 41, 215, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos9, 255)
GUI:Layout_setBackGroundImage(Panel_pos9, "")
GUI:setAnchorPoint(Panel_pos9, 0.5, 0.5)
GUI:setTag(Panel_pos9, 69)
GUI:setTouchEnabled(Panel_pos9, true)

Image_bg = GUI:Image_Create(Panel_pos9, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 70)

Image_icon = GUI:Image_Create(Panel_pos9, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015046.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 32, 34)
GUI:setTag(Image_icon, 81)

Node_item = GUI:Node_Create(Panel_pos9, "Node_item", 21, 23)
GUI:setTag(Node_item, 197)

local Panel_pos14 = GUI:Layout_Create(Panel_1, "Panel_pos14", 177, 215, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos14, 255)
GUI:Layout_setBackGroundImage(Panel_pos14, "")
GUI:setAnchorPoint(Panel_pos14, 0.5, 0.5)
GUI:setTag(Panel_pos14, 179)
GUI:setTouchEnabled(Panel_pos14, true)
GUI:setVisible(Panel_pos14, false)

Image_bg = GUI:Image_Create(Panel_pos14, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 180)

Image_icon = GUI:Image_Create(Panel_pos14, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015041.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 181)

Node_item = GUI:Node_Create(Panel_pos14, "Node_item", 21, 23)
GUI:setTag(Node_item, 192)

local Panel_pos2 = GUI:Layout_Create(Panel_1, "Panel_pos2", 221, 215, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos2, 255)
GUI:Layout_setBackGroundImage(Panel_pos2, "")
GUI:setAnchorPoint(Panel_pos2, 0.5, 0.5)
GUI:setTag(Panel_pos2, 42)
GUI:setTouchEnabled(Panel_pos2, true)

Image_bg = GUI:Image_Create(Panel_pos2, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 45)

Image_icon = GUI:Image_Create(Panel_pos2, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015033.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 76)

Node_item = GUI:Node_Create(Panel_pos2, "Node_item", 21, 23)
GUI:setTag(Node_item, 190)

local Panel_pos16 = GUI:Layout_Create(Panel_1, "Panel_pos16", 222, 436, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos16, 255)
GUI:Layout_setBackGroundImage(Panel_pos16, "")
GUI:setAnchorPoint(Panel_pos16, 0.5, 0.5)
GUI:setTag(Panel_pos16, 198)
GUI:setTouchEnabled(Panel_pos16, true)
GUI:setVisible(Panel_pos16, false)

Image_bg = GUI:Image_Create(Panel_pos16, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 199)

Image_icon = GUI:Image_Create(Panel_pos16, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015047.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 36, 36)
GUI:setTag(Image_icon, 200)

Node_item = GUI:Node_Create(Panel_pos16, "Node_item", 21, 23)
GUI:setTag(Node_item, 201)

local Panel_pos4 = GUI:Layout_Create(Panel_1, "Panel_pos4", 222, 436, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos4, 255)
GUI:Layout_setBackGroundImage(Panel_pos4, "")
GUI:setAnchorPoint(Panel_pos4, 0.5, 0.5)
GUI:setTag(Panel_pos4, 179)
GUI:setTouchEnabled(Panel_pos4, true)

Image_bg = GUI:Image_Create(Panel_pos4, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 180)

Image_icon = GUI:Image_Create(Panel_pos4, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015042.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 36, 36)
GUI:setTag(Image_icon, 181)

Node_item = GUI:Node_Create(Panel_pos4, "Node_item", 21, 23)
GUI:setTag(Node_item, 182)

local Panel_pos3 = GUI:Layout_Create(Panel_1, "Panel_pos3", 222, 347, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos3, 255)
GUI:Layout_setBackGroundImage(Panel_pos3, "")
GUI:setAnchorPoint(Panel_pos3, 0.5, 0.5)
GUI:setTag(Panel_pos3, 43)
GUI:setTouchEnabled(Panel_pos3, true)

Image_bg = GUI:Image_Create(Panel_pos3, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 44)

Image_icon = GUI:Image_Create(Panel_pos3, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015032.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 77)

Node_item = GUI:Node_Create(Panel_pos3, "Node_item", 21, 23)
GUI:setTag(Node_item, 191)

local Panel_pos6 = GUI:Layout_Create(Panel_1, "Panel_pos6", 222, 303, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos6, 255)
GUI:Layout_setBackGroundImage(Panel_pos6, "")
GUI:setAnchorPoint(Panel_pos6, 0.5, 0.5)
GUI:setTag(Panel_pos6, 34)
GUI:setTouchEnabled(Panel_pos6, true)

Image_bg = GUI:Image_Create(Panel_pos6, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 50)

Image_icon = GUI:Image_Create(Panel_pos6, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015034.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 72)

Node_item = GUI:Node_Create(Panel_pos6, "Node_item", 21, 23)
GUI:setTag(Node_item, 186)

local Panel_pos8 = GUI:Layout_Create(Panel_1, "Panel_pos8", 222, 259, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos8, 255)
GUI:Layout_setBackGroundImage(Panel_pos8, "")
GUI:setAnchorPoint(Panel_pos8, 0.5, 0.5)
GUI:setTag(Panel_pos8, 39)
GUI:setTouchEnabled(Panel_pos8, true)

Image_bg = GUI:Image_Create(Panel_pos8, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 49)

Image_icon = GUI:Image_Create(Panel_pos8, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015035.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 73)

Node_item = GUI:Node_Create(Panel_pos8, "Node_item", 21, 23)
GUI:setTag(Node_item, 187)

local Panel_pos15 = GUI:Layout_Create(Panel_1, "Panel_pos15", 364, 506, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos15, 255)
GUI:Layout_setBackGroundImage(Panel_pos15, "")
GUI:setAnchorPoint(Panel_pos15, 0.5, 0.5)
GUI:setTag(Panel_pos15, 175)
GUI:setTouchEnabled(Panel_pos15, true)
GUI:setVisible(Panel_pos15, false)

Image_bg = GUI:Image_Create(Panel_pos15, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 176)

Image_icon = GUI:Image_Create(Panel_pos15, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015040.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 177)

Node_item = GUI:Node_Create(Panel_pos15, "Node_item", 21, 23)
GUI:setTag(Node_item, 193)

local Panel_pos13 = GUI:Layout_Create(Panel_1, "Panel_pos13", 314, 560, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos13, 255)
GUI:Layout_setBackGroundImage(Panel_pos13, "")
GUI:setAnchorPoint(Panel_pos13, 0.5, 0.5)
GUI:setTag(Panel_pos13, 202)
GUI:setTouchEnabled(Panel_pos13, true)
GUI:setVisible(Panel_pos13, false)

Image_bg = GUI:Image_Create(Panel_pos13, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 203)

Image_icon = GUI:Image_Create(Panel_pos13, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015048.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 36, 36)
GUI:setTag(Image_icon, 204)

Node_item = GUI:Node_Create(Panel_pos13, "Node_item", 21, 23)
GUI:setTag(Node_item, 205)

local Panel_pos12 = GUI:Layout_Create(Panel_1, "Panel_pos12", 221, 391, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos12, 255)
GUI:Layout_setBackGroundImage(Panel_pos12, "")
GUI:setAnchorPoint(Panel_pos12, 0.5, 0.5)
GUI:setTag(Panel_pos12, 60)
GUI:setTouchEnabled(Panel_pos12, true)

Image_bg = GUI:Image_Create(Panel_pos12, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 61)

Image_icon = GUI:Image_Create(Panel_pos12, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015039.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 78)

Node_item = GUI:Node_Create(Panel_pos12, "Node_item", 21, 23)
GUI:setTag(Node_item, 194)

local Panel_pos17 = GUI:Layout_Create(Panel_1, "Panel_pos17", 448, 510, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos17, 255)
GUI:Layout_setBackGroundImage(Panel_pos17, "")
GUI:setAnchorPoint(Panel_pos17, 0.5, 0.5)
GUI:setTag(Panel_pos17, 207)
GUI:setTouchEnabled(Panel_pos17, true)
GUI:setVisible(Panel_pos17, false)

Image_bg = GUI:Image_Create(Panel_pos17, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 208)

Image_icon = GUI:Image_Create(Panel_pos17, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015041.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 209)

Node_item = GUI:Node_Create(Panel_pos17, "Node_item", 22, 22)
GUI:setTag(Node_item, 210)

local Panel_pos18 = GUI:Layout_Create(Panel_1, "Panel_pos18", 449, 452, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos18, 255)
GUI:Layout_setBackGroundImage(Panel_pos18, "")
GUI:setAnchorPoint(Panel_pos18, 0.5, 0.5)
GUI:setTag(Panel_pos18, 211)
GUI:setTouchEnabled(Panel_pos18, true)
GUI:setVisible(Panel_pos18, false)

Image_bg = GUI:Image_Create(Panel_pos18, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 212)

Image_icon = GUI:Image_Create(Panel_pos18, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015041.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 213)

Node_item = GUI:Node_Create(Panel_pos18, "Node_item", 22, 22)
GUI:setTag(Node_item, 214)

local Panel_pos19 = GUI:Layout_Create(Panel_1, "Panel_pos19", 449, 395, 45, 45, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pos19, 255)
GUI:Layout_setBackGroundImage(Panel_pos19, "")
GUI:setAnchorPoint(Panel_pos19, 0.5, 0.5)
GUI:setTag(Panel_pos19, 215)
GUI:setTouchEnabled(Panel_pos19, true)
GUI:setVisible(Panel_pos19, false)

Image_bg = GUI:Image_Create(Panel_pos19, "Image_bg", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/icon_chenghd_03.png")
GUI:setAnchorPoint(Image_bg, 0.5, 0.5)
GUI:setContentSize(Image_bg, 45, 45)
GUI:setTag(Image_bg, 216)

Image_icon = GUI:Image_Create(Panel_pos19, "Image_icon", 22, 22, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/1900015041.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 35, 36)
GUI:setTag(Image_icon, 217)

Node_item = GUI:Node_Create(Panel_pos19, "Node_item", 22, 22)
GUI:setTag(Node_item, 218)

local Node_playerModel = GUI:Layout_Create(Panel_1, "Node_playerModel", 131, 346, 40, 60, false)
GUI:Layout_setBackGroundColorOpacity(Node_playerModel, 255)
GUI:Layout_setBackGroundImage(Node_playerModel, "")
GUI:setTag(Node_playerModel, 324)

local Panel_btn_sel = GUI:Layout_Create(Panel_1, "Panel_btn_sel", 67, 588, 40, 120, false)
GUI:Layout_setBackGroundColorOpacity(Panel_btn_sel, 255)
GUI:Layout_setBackGroundImage(Panel_btn_sel, "")
GUI:setAnchorPoint(Panel_btn_sel, 0, 1)
GUI:setTag(Panel_btn_sel, 249)

local Btn_sel_1 = GUI:Button_Create(Panel_btn_sel, "Btn_sel_1", 20, 104, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_a_1.png")
GUI:Button_loadTextureDisabled(Btn_sel_1, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_l_1.png")
GUI:Button_loadTexturePressed(Btn_sel_1, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_l_1.png")
GUI:Button_setTitleFontSize(Btn_sel_1, 10)
GUI:Button_setTitleText(Btn_sel_1, "")
GUI:setAnchorPoint(Btn_sel_1, 0.5, 0.5)
GUI:setContentSize(Btn_sel_1, 38, 25)
GUI:setTag(Btn_sel_1, 439)

local Btn_sel_2 = GUI:Button_Create(Panel_btn_sel, "Btn_sel_2", 20, 76, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_a_2.png")
GUI:Button_loadTextureDisabled(Btn_sel_2, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_l_2.png")
GUI:Button_loadTexturePressed(Btn_sel_2, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_l_2.png")
GUI:Button_setTitleFontSize(Btn_sel_2, 10)
GUI:Button_setTitleText(Btn_sel_2, "")
GUI:setAnchorPoint(Btn_sel_2, 0.5, 0.5)
GUI:setContentSize(Btn_sel_2, 38, 25)
GUI:setTag(Btn_sel_2, 440)

local Btn_sel_3 = GUI:Button_Create(Panel_btn_sel, "Btn_sel_3", 20, 48, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_a_3.png")
GUI:Button_loadTextureDisabled(Btn_sel_3, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_l_3.png")
GUI:Button_loadTexturePressed(Btn_sel_3, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_l_3.png")
GUI:Button_setTitleFontSize(Btn_sel_3, 10)
GUI:Button_setTitleText(Btn_sel_3, "")
GUI:setAnchorPoint(Btn_sel_3, 0.5, 0.5)
GUI:setContentSize(Btn_sel_3, 38, 25)
GUI:setTag(Btn_sel_3, 441)

local Button_sz = GUI:Button_Create(Panel_1, "Button_sz", 130, 262, "res/private/player_main_layer_ui/player_main_layer_ui_mobile/btn_sz_2.png")
GUI:Button_loadTextureDisabled(Button_sz, "Default/Button_Disable.png")
GUI:Button_setTitleFontSize(Button_sz, 10)
GUI:Button_setTitleText(Button_sz, "")
GUI:setAnchorPoint(Button_sz, 0.5, 0.5)
GUI:setContentSize(Button_sz, 45, 45)
GUI:setTag(Button_sz, 195)
GUI:setVisible(Button_sz, false)

local FileNode_1 = GUI:FileNode_Create(Panel_1, "FileNode_1", 412, 0, "player_layer/equip", "player_layer/attr", {["bAttach"]=false,["bDrag"]=false,["bHideMain"]=false,["bSticky"]=false,["bindNpc"]=0,["exclusion"]=1,["initPos"]=1,})

 
end 
return ui