local ui = {} 
function ui.init(parent)
local Node = GUI:Node_Create(parent, "Node", 0, 0)

local Panel_1 = GUI:Layout_Create(Node, "Panel_1", -12, 6, 672, 138, false)
GUI:Layout_setBackGroundColorOpacity(Panel_1, 255)
GUI:Layout_setBackGroundImage(Panel_1, "")
GUI:setAnchorPoint(Panel_1, 0.5, 0)
GUI:setTag(Panel_1, 24)

local Panel_dynamic = GUI:Layout_Create(Panel_1, "Panel_dynamic", 0, 1, 672, 140, false)
GUI:Layout_setBackGroundColorOpacity(Panel_dynamic, 255)
GUI:Layout_setBackGroundImage(Panel_dynamic, "")
GUI:setTag(Panel_dynamic, 26)

local Panel_large = GUI:Layout_Create(Panel_dynamic, "Panel_large", -1, 0, 671, 306.64999389648, false)
GUI:Layout_setBackGroundColorOpacity(Panel_large, 255)
GUI:Layout_setBackGroundImage(Panel_large, "")
GUI:setTag(Panel_large, 34)
GUI:setTouchEnabled(Panel_large, true)

local Image_large_left = GUI:Image_Create(Panel_large, "Image_large_left", 0, 0, "res/private/main_win32/chat/bg_large_left.png")
GUI:setContentSize(Image_large_left, 401, 298)
GUI:setTag(Image_large_left, 31)

local Image_large_right = GUI:Image_Create(Panel_large, "Image_large_right", 675, 0, "res/private/main_win32/chat/bg_large_right.png")
GUI:setAnchorPoint(Image_large_right, 1, 0)
GUI:setContentSize(Image_large_right, 376, 298)
GUI:setTag(Image_large_right, 33)

local Image_large_mid = GUI:Image_Create(Panel_large, "Image_large_mid", 337, 0, "res/private/main_win32/chat/bg_large_mid.png")
GUI:setAnchorPoint(Image_large_mid, 0.5, 0)
GUI:setContentSize(Image_large_mid, 151, 319)
GUI:setTag(Image_large_mid, 32)

local img_large_rainbow = GUI:Image_Create(Image_large_mid, "img_large_rainbow", 75, 302, "res/private/main/rainbow_1.png")
GUI:setAnchorPoint(img_large_rainbow, 0.5, 0.5)
GUI:setContentSize(img_large_rainbow, 36, 20)
GUI:setTag(img_large_rainbow, 123)

local Text_level = GUI:Text_Create(Image_large_mid, "Text_level", 75, 294, 14, "#FFFFFF", "999")
GUI:Text_enableOutline(Text_level, "#000000", 1)
GUI:setAnchorPoint(Text_level, 0.5, 0.5)
GUI:setContentSize(Text_level, 24, 18)
GUI:setIgnoreContentAdaptWithSize(Text_level, true)
GUI:setTag(Text_level, 304)

local Panel_e_large = GUI:Button_Create(Panel_large, "Panel_e_large", 658, 278, "res/private/main_win32/chat/img_blue.png")
GUI:Button_setTitleFontSize(Panel_e_large, 10)
GUI:Button_setTitleText(Panel_e_large, "")
GUI:setContentSize(Panel_e_large, 14, 16)

local ScrollView_msg = GUI:ScrollView_Create(Panel_large, "ScrollView_msg", 9, 75, 640, 204, 1)
GUI:Layout_setBackGroundColorOpacity(ScrollView_msg, 255)
GUI:Layout_setBackGroundImage(ScrollView_msg, "")
GUI:Layout_setClippingEnabled(ScrollView_msg, true)
GUI:ScrollView_setInnerContainerSize(ScrollView_msg, 640, 204)
GUI:setTag(ScrollView_msg, 97)
GUI:setTouchEnabled(ScrollView_msg, true)

local Slider_chart = GUI:Slider_Create(Panel_large, "Slider_chart", 668, 258, "", "", "res/private/main_win32/chat/img_slider_1.png")
GUI:Slider_setPercent(Slider_chart, 100)
GUI:setAnchorPoint(Slider_chart, 0, 0.5)
GUI:setContentSize(Slider_chart, 197, 16)
GUI:setRotation(Slider_chart, 90)
GUI:setRotationSkewX(Slider_chart, 90)
GUI:setRotationSkewY(Slider_chart, 90)
GUI:setTag(Slider_chart, 257)
GUI:setTouchEnabled(Slider_chart, true)

local Panel_small = GUI:Layout_Create(Panel_dynamic, "Panel_small", -1, 0, 671, 155.7799987793, false)
GUI:Layout_setBackGroundColorOpacity(Panel_small, 255)
GUI:Layout_setBackGroundImage(Panel_small, "")
GUI:setTag(Panel_small, 35)
GUI:setTouchEnabled(Panel_small, true)

local Image_left = GUI:Image_Create(Panel_small, "Image_left", 0, 0, "res/private/main_win32/chat/bg_small_left.png")
GUI:setContentSize(Image_left, 364, 131)
GUI:setTag(Image_left, 36)

local Image_right = GUI:Image_Create(Panel_small, "Image_right", 674, 0, "res/private/main_win32/chat/bg_small_right.png")
GUI:setAnchorPoint(Image_right, 1, 0)
GUI:setContentSize(Image_right, 353, 131)
GUI:setTag(Image_right, 38)

local Panel_2 = GUI:Layout_Create(Image_right, "Panel_2", 370, 18, 85, 86.959999084473, false)
GUI:Layout_setBackGroundColor(Panel_2, "#000000")
GUI:Layout_setBackGroundColorOpacity(Panel_2, 255)
GUI:Layout_setBackGroundColorType(Panel_2, 1)
GUI:Layout_setBackGroundImage(Panel_2, "")
GUI:setAnchorPoint(Panel_2, 1, 0)
GUI:setTag(Panel_2, 82)
GUI:setTouchEnabled(Panel_2, true)
GUI:setVisible(Panel_2, false)

local Image_mid = GUI:Image_Create(Panel_small, "Image_mid", 337, -0, "res/private/main_win32/chat/bg_small_mid.png")
GUI:setAnchorPoint(Image_mid, 0.5, 0)
GUI:setContentSize(Image_mid, 210, 152)
GUI:setTag(Image_mid, 37)

local img_small_rainbow = GUI:Image_Create(Image_mid, "img_small_rainbow", 102, 135, "res/private/main/rainbow_1.png")
GUI:setAnchorPoint(img_small_rainbow, 0.5, 0.5)
GUI:setContentSize(img_small_rainbow, 36, 20)
GUI:setTag(img_small_rainbow, 123)

Text_level = GUI:Text_Create(Image_mid, "Text_level", 101, 127, 14, "#FFFFFF", "999")
GUI:Text_enableOutline(Text_level, "#000000", 1)
GUI:setAnchorPoint(Text_level, 0.5, 0.5)
GUI:setContentSize(Text_level, 24, 18)
GUI:setIgnoreContentAdaptWithSize(Text_level, true)
GUI:setTag(Text_level, 303)

ScrollView_msg = GUI:ScrollView_Create(Panel_small, "ScrollView_msg", 12, 38, 640, 75, 1)
GUI:Layout_setBackGroundColorOpacity(ScrollView_msg, 255)
GUI:Layout_setBackGroundImage(ScrollView_msg, "")
GUI:Layout_setClippingEnabled(ScrollView_msg, true)
GUI:ScrollView_setInnerContainerSize(ScrollView_msg, 640, 84)
GUI:setTag(ScrollView_msg, 98)
GUI:setTouchEnabled(ScrollView_msg, true)

local Image_head = GUI:Image_Create(Panel_small, "Image_head", 616, 66, "res/MonImg/1999.png")
GUI:setAnchorPoint(Image_head, 0.5, 0.5)
GUI:setContentSize(Image_head, 84, 94)
GUI:setTag(Image_head, 40)
GUI:setTouchEnabled(Image_head, true)

local Image_race = GUI:Image_Create(Image_head, "Image_race", 75, 8, "res/private/main/Target/icon_3.png")
GUI:setAnchorPoint(Image_race, 0.5, 0.5)
GUI:setContentSize(Image_race, 13, 13)
GUI:setTag(Image_race, 93)

local nd_minimap = GUI:Widget_Create(Panel_small, "nd_minimap", 616, 66, 0, 0)

local main_ui_win32_chatMiniMap_win32 = GUI:FileNode_Create(nd_minimap, "main_ui_win32_chatMiniMap_win32", 0, 0, "main_ui_win32/chat_win32", "main_ui_win32/chatMiniMap_win32", {["bAttach"]=false,["bDrag"]=false,["bHideMain"]=false,["bSticky"]=false,["bindNpc"]=0,["exclusion"]=1,["initPos"]=1,})

local Panel_property = GUI:Layout_Create(Panel_small, "Panel_property", 672, 131, 132, 90, false)
GUI:Layout_setBackGroundColor(Panel_property, "#2C443B")
GUI:Layout_setBackGroundColorOpacity(Panel_property, 191)
GUI:Layout_setBackGroundColorType(Panel_property, 1)
GUI:Layout_setBackGroundImage(Panel_property, "")
GUI:setAnchorPoint(Panel_property, 0, 1)
GUI:setTag(Panel_property, 83)
GUI:setTouchEnabled(Panel_property, true)

local Image_dominate = GUI:Image_Create(Panel_property, "Image_dominate", 11, 78, "res/private/main/Target/icon_2.png")
GUI:setAnchorPoint(Image_dominate, 0.5, 0.5)
GUI:setContentSize(Image_dominate, 20, 20)
GUI:setTag(Image_dominate, 84)

local Image_attack = GUI:Image_Create(Panel_property, "Image_attack", 32, 78, "res/private/main/Target/icon_l_7.png")
GUI:setAnchorPoint(Image_attack, 0.5, 0.5)
GUI:setContentSize(Image_attack, 20, 20)
GUI:setTag(Image_attack, 85)

local Image_move = GUI:Image_Create(Panel_property, "Image_move", 54, 78, "res/private/main/Target/speed_0.png")
GUI:setAnchorPoint(Image_move, 0.5, 0.5)
GUI:setContentSize(Image_move, 20, 20)
GUI:setTag(Image_move, 86)

local Image_attr_1 = GUI:Image_Create(Panel_property, "Image_attr_1", 14, 56, "res/private/main/Target/icon_l_1.png")
GUI:setAnchorPoint(Image_attr_1, 0.5, 0.5)
GUI:setContentSize(Image_attr_1, 20, 20)
GUI:setTag(Image_attr_1, 87)

local Text_val = GUI:Text_Create(Image_attr_1, "Text_val", 29, 10, 14, "#FFFFFF", "+0")
GUI:Text_enableOutline(Text_val, "#000000", 0)
GUI:setAnchorPoint(Text_val, 0.5, 0.5)
GUI:setContentSize(Text_val, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_val, true)
GUI:setTag(Text_val, 88)

local Image_attr_2 = GUI:Image_Create(Panel_property, "Image_attr_2", 57, 56, "res/private/main/Target/icon_l_2.png")
GUI:setAnchorPoint(Image_attr_2, 0.5, 0.5)
GUI:setContentSize(Image_attr_2, 20, 20)
GUI:setTag(Image_attr_2, 94)

Text_val = GUI:Text_Create(Image_attr_2, "Text_val", 29, 10, 14, "#FFFFFF", "+0")
GUI:Text_enableOutline(Text_val, "#000000", 0)
GUI:setAnchorPoint(Text_val, 0.5, 0.5)
GUI:setContentSize(Text_val, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_val, true)
GUI:setTag(Text_val, 95)

local Image_attr_3 = GUI:Image_Create(Panel_property, "Image_attr_3", 99, 56, "res/private/main/Target/icon_l_3.png")
GUI:setAnchorPoint(Image_attr_3, 0.5, 0.5)
GUI:setContentSize(Image_attr_3, 20, 20)
GUI:setTag(Image_attr_3, 96)

Text_val = GUI:Text_Create(Image_attr_3, "Text_val", 29, 10, 14, "#FFFFFF", "+0")
GUI:Text_enableOutline(Text_val, "#000000", 0)
GUI:setAnchorPoint(Text_val, 0.5, 0.5)
GUI:setContentSize(Text_val, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_val, true)
GUI:setTag(Text_val, 97)

local Image_attr_4 = GUI:Image_Create(Panel_property, "Image_attr_4", 14, 34, "res/private/main/Target/icon_l_4.png")
GUI:setAnchorPoint(Image_attr_4, 0.5, 0.5)
GUI:setContentSize(Image_attr_4, 20, 20)
GUI:setTag(Image_attr_4, 98)

Text_val = GUI:Text_Create(Image_attr_4, "Text_val", 29, 10, 14, "#FFFFFF", "+0")
GUI:Text_enableOutline(Text_val, "#000000", 0)
GUI:setAnchorPoint(Text_val, 0.5, 0.5)
GUI:setContentSize(Text_val, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_val, true)
GUI:setTag(Text_val, 99)

local Image_attr_5 = GUI:Image_Create(Panel_property, "Image_attr_5", 57, 34, "res/private/main/Target/icon_l_5.png")
GUI:setAnchorPoint(Image_attr_5, 0.5, 0.5)
GUI:setContentSize(Image_attr_5, 20, 20)
GUI:setTag(Image_attr_5, 100)

Text_val = GUI:Text_Create(Image_attr_5, "Text_val", 29, 10, 14, "#FFFFFF", "+0")
GUI:Text_enableOutline(Text_val, "#000000", 0)
GUI:setAnchorPoint(Text_val, 0.5, 0.5)
GUI:setContentSize(Text_val, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_val, true)
GUI:setTag(Text_val, 101)

local Image_attr_6 = GUI:Image_Create(Panel_property, "Image_attr_6", 99, 34, "res/private/main/Target/icon_l_6.png")
GUI:setAnchorPoint(Image_attr_6, 0.5, 0.5)
GUI:setContentSize(Image_attr_6, 20, 20)
GUI:setTag(Image_attr_6, 102)

Text_val = GUI:Text_Create(Image_attr_6, "Text_val", 29, 10, 14, "#FFFFFF", "+0")
GUI:Text_enableOutline(Text_val, "#000000", 0)
GUI:setAnchorPoint(Text_val, 0.5, 0.5)
GUI:setContentSize(Text_val, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_val, true)
GUI:setTag(Text_val, 103)

local Image_attr_7 = GUI:Image_Create(Panel_property, "Image_attr_7", 14, 11, "res/private/main/Target/icon_ys_7.png")
GUI:setAnchorPoint(Image_attr_7, 0.5, 0.5)
GUI:setContentSize(Image_attr_7, 20, 20)
GUI:setTag(Image_attr_7, 104)

Text_val = GUI:Text_Create(Image_attr_7, "Text_val", 29, 10, 14, "#FFFFFF", "+0")
GUI:Text_enableOutline(Text_val, "#000000", 0)
GUI:setAnchorPoint(Text_val, 0.5, 0.5)
GUI:setContentSize(Text_val, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_val, true)
GUI:setTag(Text_val, 105)

local Panel_e_small = GUI:Button_Create(Panel_small, "Panel_e_small", 658, 111, "res/private/main_win32/chat/img_blue.png")
GUI:Button_setTitleFontSize(Panel_e_small, 10)
GUI:Button_setTitleText(Panel_e_small, "")
GUI:setContentSize(Panel_e_small, 14, 16)

local Slider_small_chart = GUI:Slider_Create(Panel_small, "Slider_small_chart", 668, 91, "", "", "res/private/main_win32/chat/img_slider_1.png")
GUI:Slider_setPercent(Slider_small_chart, 80)
GUI:setAnchorPoint(Slider_small_chart, 0, 0.5)
GUI:setContentSize(Slider_small_chart, 60, 16)
GUI:setRotation(Slider_small_chart, 90)
GUI:setRotationSkewX(Slider_small_chart, 90)
GUI:setRotationSkewY(Slider_small_chart, 90)
GUI:setTouchEnabled(Slider_small_chart, true)

local ListView_chat_ex = GUI:ListView_Create(Panel_dynamic, "ListView_chat_ex", 12, 114, 550, 23, 1)
GUI:Layout_setBackGroundColorOpacity(ListView_chat_ex, 255)
GUI:Layout_setBackGroundImage(ListView_chat_ex, "")
GUI:Layout_setClippingEnabled(ListView_chat_ex, true)
GUI:ListView_setGravity(ListView_chat_ex, 5)
GUI:setAnchorPoint(ListView_chat_ex, 0, 1)

local Panel_chanel_filter = GUI:Layout_Create(Panel_1, "Panel_chanel_filter", 0, -4, 406, 50, false)
GUI:Layout_setBackGroundColorOpacity(Panel_chanel_filter, 255)
GUI:Layout_setBackGroundImage(Panel_chanel_filter, "")
GUI:setTag(Panel_chanel_filter, 41)

local Image_common = GUI:Image_Create(Panel_chanel_filter, "Image_common", 24, 26, "res/private/main_win32/chat/img_new_btn.png")
GUI:setAnchorPoint(Image_common, 0.5, 0.5)
GUI:setContentSize(Image_common, 52, 38)
GUI:setTag(Image_common, 43)
GUI:setTouchEnabled(Image_common, true)

local img_select = GUI:Image_Create(Image_common, "img_select", 26, 19, "res/private/main_win32/chat/img_select.png")
GUI:setAnchorPoint(img_select, 0.5, 0.5)
GUI:setContentSize(img_select, 52, 40)
GUI:setVisible(img_select, false)

local cb_chat = GUI:CheckBox_Create(Image_common, "cb_chat", 15, 18, "res/private/main_win32/chat/img_green_bg.png", "res/private/main_win32/chat/img_gree.png")
GUI:setAnchorPoint(cb_chat, 0.5, 0.5)
GUI:setContentSize(cb_chat, 16, 16)

local img_icon = GUI:Image_Create(Image_common, "img_icon", 36, 18, "res/private/main_win32/chat/font_all_1.png")
GUI:setAnchorPoint(img_icon, 0.5, 0.5)
GUI:setContentSize(img_icon, 18, 18)

local Image_system = GUI:Image_Create(Panel_chanel_filter, "Image_system", 78, 26, "res/private/main_win32/chat/img_new_btn.png")
GUI:setAnchorPoint(Image_system, 0.5, 0.5)
GUI:setContentSize(Image_system, 52, 38)
GUI:setTag(Image_system, 43)
GUI:setTouchEnabled(Image_system, true)

img_select = GUI:Image_Create(Image_system, "img_select", 26, 19, "res/private/main_win32/chat/img_select.png")
GUI:setAnchorPoint(img_select, 0.5, 0.5)
GUI:setContentSize(img_select, 52, 40)
GUI:setVisible(img_select, false)

cb_chat = GUI:CheckBox_Create(Image_system, "cb_chat", 15, 18, "res/private/main_win32/chat/img_green_bg.png", "res/private/main_win32/chat/img_gree.png")
GUI:setAnchorPoint(cb_chat, 0.5, 0.5)
GUI:setContentSize(cb_chat, 16, 16)

img_icon = GUI:Image_Create(Image_system, "img_icon", 36, 18, "res/private/main_win32/chat/font_system_1.png")
GUI:setAnchorPoint(img_icon, 0.5, 0.5)
GUI:setContentSize(img_icon, 18, 18)

local Image_shout = GUI:Image_Create(Panel_chanel_filter, "Image_shout", 132, 26, "res/private/main_win32/chat/img_new_btn.png")
GUI:setAnchorPoint(Image_shout, 0.5, 0.5)
GUI:setContentSize(Image_shout, 52, 38)
GUI:setTag(Image_shout, 43)
GUI:setTouchEnabled(Image_shout, true)

img_select = GUI:Image_Create(Image_shout, "img_select", 26, 19, "res/private/main_win32/chat/img_select.png")
GUI:setAnchorPoint(img_select, 0.5, 0.5)
GUI:setContentSize(img_select, 52, 40)
GUI:setVisible(img_select, false)

cb_chat = GUI:CheckBox_Create(Image_shout, "cb_chat", 15, 18, "res/private/main_win32/chat/img_green_bg.png", "res/private/main_win32/chat/img_gree.png")
GUI:setAnchorPoint(cb_chat, 0.5, 0.5)
GUI:setContentSize(cb_chat, 16, 16)

img_icon = GUI:Image_Create(Image_shout, "img_icon", 36, 18, "res/private/main_win32/chat/font_shout_1.png")
GUI:setAnchorPoint(img_icon, 0.5, 0.5)
GUI:setContentSize(img_icon, 18, 18)

local Image_private = GUI:Image_Create(Panel_chanel_filter, "Image_private", 186, 26, "res/private/main_win32/chat/img_new_btn.png")
GUI:setAnchorPoint(Image_private, 0.5, 0.5)
GUI:setContentSize(Image_private, 52, 38)
GUI:setTag(Image_private, 43)
GUI:setTouchEnabled(Image_private, true)

img_select = GUI:Image_Create(Image_private, "img_select", 26, 19, "res/private/main_win32/chat/img_select.png")
GUI:setAnchorPoint(img_select, 0.5, 0.5)
GUI:setContentSize(img_select, 52, 40)
GUI:setVisible(img_select, false)

cb_chat = GUI:CheckBox_Create(Image_private, "cb_chat", 15, 18, "res/private/main_win32/chat/img_green_bg.png", "res/private/main_win32/chat/img_gree.png")
GUI:setAnchorPoint(cb_chat, 0.5, 0.5)
GUI:setContentSize(cb_chat, 16, 16)

img_icon = GUI:Image_Create(Image_private, "img_icon", 36, 18, "res/private/main_win32/chat/font_person_1.png")
GUI:setAnchorPoint(img_icon, 0.5, 0.5)
GUI:setContentSize(img_icon, 18, 18)

local Image_guild = GUI:Image_Create(Panel_chanel_filter, "Image_guild", 240, 26, "res/private/main_win32/chat/img_new_btn.png")
GUI:setAnchorPoint(Image_guild, 0.5, 0.5)
GUI:setContentSize(Image_guild, 52, 38)
GUI:setTag(Image_guild, 43)
GUI:setTouchEnabled(Image_guild, true)

img_select = GUI:Image_Create(Image_guild, "img_select", 26, 19, "res/private/main_win32/chat/img_select.png")
GUI:setAnchorPoint(img_select, 0.5, 0.5)
GUI:setContentSize(img_select, 52, 40)
GUI:setVisible(img_select, false)

cb_chat = GUI:CheckBox_Create(Image_guild, "cb_chat", 15, 18, "res/private/main_win32/chat/img_green_bg.png", "res/private/main_win32/chat/img_gree.png")
GUI:setAnchorPoint(cb_chat, 0.5, 0.5)
GUI:setContentSize(cb_chat, 16, 16)

img_icon = GUI:Image_Create(Image_guild, "img_icon", 36, 18, "res/private/main_win32/chat/font_guid_1.png")
GUI:setAnchorPoint(img_icon, 0.5, 0.5)
GUI:setContentSize(img_icon, 18, 18)

local Image_team = GUI:Image_Create(Panel_chanel_filter, "Image_team", 294, 26, "res/private/main_win32/chat/img_new_btn.png")
GUI:setAnchorPoint(Image_team, 0.5, 0.5)
GUI:setContentSize(Image_team, 52, 38)
GUI:setTag(Image_team, 43)
GUI:setTouchEnabled(Image_team, true)

img_select = GUI:Image_Create(Image_team, "img_select", 26, 19, "res/private/main_win32/chat/img_select.png")
GUI:setAnchorPoint(img_select, 0.5, 0.5)
GUI:setContentSize(img_select, 52, 40)
GUI:setVisible(img_select, false)

cb_chat = GUI:CheckBox_Create(Image_team, "cb_chat", 15, 18, "res/private/main_win32/chat/img_green_bg.png", "res/private/main_win32/chat/img_gree.png")
GUI:setAnchorPoint(cb_chat, 0.5, 0.5)
GUI:setContentSize(cb_chat, 16, 16)

img_icon = GUI:Image_Create(Image_team, "img_icon", 36, 18, "res/private/main_win32/chat/font_cp_1.png")
GUI:setAnchorPoint(img_icon, 0.5, 0.5)
GUI:setContentSize(img_icon, 18, 18)

local Image_near = GUI:Image_Create(Panel_chanel_filter, "Image_near", 348, 26, "res/private/main_win32/chat/img_new_btn.png")
GUI:setAnchorPoint(Image_near, 0.5, 0.5)
GUI:setContentSize(Image_near, 52, 38)
GUI:setTag(Image_near, 43)
GUI:setTouchEnabled(Image_near, true)

img_select = GUI:Image_Create(Image_near, "img_select", 26, 19, "res/private/main_win32/chat/img_select.png")
GUI:setAnchorPoint(img_select, 0.5, 0.5)
GUI:setContentSize(img_select, 52, 40)
GUI:setVisible(img_select, false)

cb_chat = GUI:CheckBox_Create(Image_near, "cb_chat", 15, 18, "res/private/main_win32/chat/img_green_bg.png", "res/private/main_win32/chat/img_gree.png")
GUI:setAnchorPoint(cb_chat, 0.5, 0.5)
GUI:setContentSize(cb_chat, 16, 16)

img_icon = GUI:Image_Create(Image_near, "img_icon", 36, 18, "res/private/main_win32/chat/font_add_1.png")
GUI:setAnchorPoint(img_icon, 0.5, 0.5)
GUI:setContentSize(img_icon, 18, 18)

local Image_world = GUI:Image_Create(Panel_chanel_filter, "Image_world", 402, 26, "res/private/main_win32/chat/img_new_btn.png")
GUI:setAnchorPoint(Image_world, 0.5, 0.5)
GUI:setContentSize(Image_world, 52, 38)
GUI:setTag(Image_world, 43)
GUI:setTouchEnabled(Image_world, true)

img_select = GUI:Image_Create(Image_world, "img_select", 26, 19, "res/private/main_win32/chat/img_select.png")
GUI:setAnchorPoint(img_select, 0.5, 0.5)
GUI:setContentSize(img_select, 52, 40)
GUI:setVisible(img_select, false)

cb_chat = GUI:CheckBox_Create(Image_world, "cb_chat", 15, 18, "res/private/main_win32/chat/img_green_bg.png", "res/private/main_win32/chat/img_gree.png")
GUI:setAnchorPoint(cb_chat, 0.5, 0.5)
GUI:setContentSize(cb_chat, 16, 16)

img_icon = GUI:Image_Create(Image_world, "img_icon", 36, 18, "res/private/main_win32/chat/font_world_1.png")
GUI:setAnchorPoint(img_icon, 0.5, 0.5)
GUI:setContentSize(img_icon, 18, 18)

local Image_drop = GUI:Image_Create(Panel_chanel_filter, "Image_drop", 456, 26, "res/private/main_win32/chat/img_new_btn.png")
GUI:setAnchorPoint(Image_drop, 0.5, 0.5)
GUI:setContentSize(Image_drop, 52, 38)
GUI:setTag(Image_drop, 43)
GUI:setTouchEnabled(Image_drop, true)

img_select = GUI:Image_Create(Image_drop, "img_select", 26, 19, "res/private/main_win32/chat/img_select.png")
GUI:setAnchorPoint(img_select, 0.5, 0.5)
GUI:setContentSize(img_select, 52, 40)
GUI:setVisible(img_select, false)

cb_chat = GUI:CheckBox_Create(Image_drop, "cb_chat", 15, 18, "res/private/main_win32/chat/img_green_bg.png", "res/private/main_win32/chat/img_gree.png")
GUI:setAnchorPoint(cb_chat, 0.5, 0.5)
GUI:setContentSize(cb_chat, 16, 16)

img_icon = GUI:Image_Create(Image_drop, "img_icon", 36, 18, "res/private/main_win32/chat/font_drop_1.png")
GUI:setAnchorPoint(img_icon, 0.5, 0.5)
GUI:setContentSize(img_icon, 18, 18)

local Panel_function_dynamic = GUI:Layout_Create(Panel_1, "Panel_function_dynamic", 680, -2, 192, 54, false)
GUI:Layout_setBackGroundColorOpacity(Panel_function_dynamic, 255)
GUI:Layout_setBackGroundImage(Panel_function_dynamic, "")
GUI:setAnchorPoint(Panel_function_dynamic, 1, 0)
GUI:setTag(Panel_function_dynamic, 66)

local Button_bag = GUI:Button_Create(Panel_function_dynamic, "Button_bag", 20, 25, "res/private/main_win32/chat/btn_bag_1.png")
GUI:Button_loadTexturePressed(Button_bag, "res/private/main_win32/chat/btn_bag_2.png")
GUI:Button_setScale9Slice(Button_bag, 15.000000953674, 15, 10.999999046326, 11.000000953674)
GUI:Button_setTitleColor(Button_bag, "#414146")
GUI:Button_setTitleFontSize(Button_bag, 10)
GUI:Button_setTitleText(Button_bag, "")
GUI:setAnchorPoint(Button_bag, 0.5, 0.5)
GUI:setContentSize(Button_bag, 38, 38)
GUI:setTag(Button_bag, 67)

local Button_emoji = GUI:Button_Create(Panel_function_dynamic, "Button_emoji", 65, 25, "res/private/main_win32/chat/btn_emoji_1.png")
GUI:Button_loadTexturePressed(Button_emoji, "res/private/main_win32/chat/btn_emoji_2.png")
GUI:Button_setScale9Slice(Button_emoji, 15.000000953674, 15, 10.999999046326, 11.000000953674)
GUI:Button_setTitleColor(Button_emoji, "#414146")
GUI:Button_setTitleFontSize(Button_emoji, 10)
GUI:Button_setTitleText(Button_emoji, "")
GUI:setAnchorPoint(Button_emoji, 0.5, 0.5)
GUI:setContentSize(Button_emoji, 38, 38)
GUI:setTag(Button_emoji, 70)

local Button_history = GUI:Button_Create(Panel_function_dynamic, "Button_history", 111, 25, "res/private/main_win32/chat/btn_his_1.png")
GUI:Button_loadTexturePressed(Button_history, "res/private/main_win32/chat/btn_his_2.png")
GUI:Button_setScale9Slice(Button_history, 15.000000953674, 15, 10.999999046326, 11.000000953674)
GUI:Button_setTitleColor(Button_history, "#414146")
GUI:Button_setTitleFontSize(Button_history, 10)
GUI:Button_setTitleText(Button_history, "")
GUI:setAnchorPoint(Button_history, 0.5, 0.5)
GUI:setContentSize(Button_history, 38, 38)
GUI:setTag(Button_history, 71)

local Button_coordinate = GUI:Button_Create(Panel_function_dynamic, "Button_coordinate", 157, 25, "res/private/main_win32/chat/btn_coordinate_1.png")
GUI:Button_loadTexturePressed(Button_coordinate, "res/private/main_win32/chat/btn_coordinate_2.png")
GUI:Button_setScale9Slice(Button_coordinate, 15.000000953674, 15, 10.999999046326, 11.000000953674)
GUI:Button_setTitleColor(Button_coordinate, "#414146")
GUI:Button_setTitleFontSize(Button_coordinate, 10)
GUI:Button_setTitleText(Button_coordinate, "")
GUI:setAnchorPoint(Button_coordinate, 0.5, 0.5)
GUI:setContentSize(Button_coordinate, 38, 38)
GUI:setTag(Button_coordinate, 72)

local Panel_input = GUI:Layout_Create(Panel_1, "Panel_input", 1, 5, 560, 28, false)
GUI:Layout_setBackGroundColorOpacity(Panel_input, 255)
GUI:Layout_setBackGroundImage(Panel_input, "")
GUI:setTag(Panel_input, 181)
GUI:setTouchEnabled(Panel_input, true)

local Image_chanel = GUI:Image_Create(Panel_input, "Image_chanel", 30, 16, "res/private/main_win32/chat_input/font_around.png")
GUI:setAnchorPoint(Image_chanel, 0.5, 0.5)
GUI:setContentSize(Image_chanel, 32, 14)
GUI:setTag(Image_chanel, 184)
GUI:setTouchEnabled(Image_chanel, true)

local Button_switch_show = GUI:Button_Create(Panel_input, "Button_switch_show", 57, 15, "res/private/main_win32/chat_input/flag_down.png")
GUI:Button_setScale9Slice(Button_switch_show, 3, 3, 3.9999997615814, 4.0000002384186)
GUI:Button_setTitleColor(Button_switch_show, "#414146")
GUI:Button_setTitleFontSize(Button_switch_show, 10)
GUI:Button_setTitleText(Button_switch_show, "")
GUI:setAnchorPoint(Button_switch_show, 0.5, 0.5)
GUI:setContentSize(Button_switch_show, 22, 18)
GUI:setRotation(Button_switch_show, 180)
GUI:setRotationSkewX(Button_switch_show, 180)
GUI:setRotationSkewY(Button_switch_show, 180)
GUI:setTag(Button_switch_show, 81)

local Button_switch_hide = GUI:Button_Create(Panel_input, "Button_switch_hide", 57, 16, "res/private/main_win32/chat_input/flag_down.png")
GUI:Button_setScale9Slice(Button_switch_hide, 3, 3, 3.9999997615814, 4.0000002384186)
GUI:Button_setTitleColor(Button_switch_hide, "#414146")
GUI:Button_setTitleFontSize(Button_switch_hide, 10)
GUI:Button_setTitleText(Button_switch_hide, "")
GUI:setAnchorPoint(Button_switch_hide, 0.5, 0.5)
GUI:setContentSize(Button_switch_hide, 22, 18)
GUI:setTag(Button_switch_hide, 82)

local img_input_bg = GUI:Image_Create(Panel_input, "img_input_bg", 120, 14, "res/private/main_win32/chat_input/input_bg.png")
GUI:setAnchorPoint(img_input_bg, 0.5, 0.5)
GUI:setContentSize(img_input_bg, 94, 26)
GUI:setVisible(img_input_bg, false)

local img_lb_bg = GUI:Image_Create(Panel_input, "img_lb_bg", 71, 6, "res/private/main_win32/chat/img_lb_bg.png")
GUI:setContentSize(img_lb_bg, 50, 20)
GUI:setTouchEnabled(img_lb_bg, true)
GUI:setVisible(img_lb_bg, false)

local img_txt_lb = GUI:Image_Create(img_lb_bg, "img_txt_lb", 25, 10, "res/private/main_win32/chat/img_txt_lb.png")
GUI:setAnchorPoint(img_txt_lb, 0.5, 0.5)
GUI:setContentSize(img_txt_lb, 36, 24)

local TextField_input = GUI:TextInput_Create(Panel_input, "TextField_input", 69, 8, 490, 14, 12)
GUI:TextInput_setPlaceHolder(TextField_input, "Text Field")
GUI:setTag(TextField_input, 96)
GUI:setTouchEnabled(TextField_input, true)

local ScrollView_chanelbg = GUI:Image_Create(Panel_input, "ScrollView_chanelbg", 27, 30, "res/public/1900000651_3.png")
GUI:Image_setScale9Enabled(ScrollView_chanelbg, true)
GUI:Image_setScale9Slice(ScrollView_chanelbg, 23, 23, 22.000007629395, 21.999996185303)
GUI:setAnchorPoint(ScrollView_chanelbg, 0.5, 0)
GUI:setContentSize(ScrollView_chanelbg, 60, 150)
GUI:setTag(ScrollView_chanelbg, 141)
GUI:setVisible(ScrollView_chanelbg, false)

local ScrollView_chanel = GUI:ScrollView_Create(ScrollView_chanelbg, "ScrollView_chanel", 30, 12, 60, 125, 1)
GUI:Layout_setBackGroundColorOpacity(ScrollView_chanel, 255)
GUI:Layout_setBackGroundImage(ScrollView_chanel, "")
GUI:Layout_setClippingEnabled(ScrollView_chanel, true)
GUI:ScrollView_setInnerContainerSize(ScrollView_chanel, 60, 125)
GUI:setAnchorPoint(ScrollView_chanel, 0.5, 0)
GUI:setTag(ScrollView_chanel, 83)
GUI:setTouchEnabled(ScrollView_chanel, true)

local Image_nearbg = GUI:Layout_Create(ScrollView_chanel, "Image_nearbg", 0, 160, 60, 25, false)
GUI:Layout_setBackGroundColorOpacity(Image_nearbg, 255)
GUI:Layout_setBackGroundImage(Image_nearbg, "")
GUI:setTag(Image_nearbg, 130)
GUI:setTouchEnabled(Image_nearbg, true)

local Image_near_color = GUI:Layout_Create(Image_nearbg, "Image_near_color", 30, 12, 50, 25, false)
GUI:Layout_setBackGroundColor(Image_near_color, "#7BFF3D")
GUI:Layout_setBackGroundColorOpacity(Image_near_color, 50)
GUI:Layout_setBackGroundColorType(Image_near_color, 1)
GUI:Layout_setBackGroundImage(Image_near_color, "")
GUI:setAnchorPoint(Image_near_color, 0.5, 0.5)
GUI:setTag(Image_near_color, 224)
GUI:setTouchEnabled(Image_near_color, true)
GUI:setVisible(Image_near_color, false)

Image_near = GUI:Image_Create(Image_nearbg, "Image_near", 30, 12, "res/private/main_win32/chat_input/font_around.png")
GUI:setAnchorPoint(Image_near, 0.5, 0.5)
GUI:setContentSize(Image_near, 32, 14)
GUI:setTag(Image_near, 84)
GUI:setTouchEnabled(Image_near, true)

local Image_dropbg = GUI:Layout_Create(ScrollView_chanel, "Image_dropbg", 0, 140, 60, 25, false)
GUI:Layout_setBackGroundColorOpacity(Image_dropbg, 255)
GUI:Layout_setBackGroundImage(Image_dropbg, "")
GUI:setTag(Image_dropbg, 131)
GUI:setTouchEnabled(Image_dropbg, true)

local Image_drop_color = GUI:Layout_Create(Image_dropbg, "Image_drop_color", 30, 12, 50, 25, false)
GUI:Layout_setBackGroundColor(Image_drop_color, "#7BFF3D")
GUI:Layout_setBackGroundColorOpacity(Image_drop_color, 50)
GUI:Layout_setBackGroundColorType(Image_drop_color, 1)
GUI:Layout_setBackGroundImage(Image_drop_color, "")
GUI:setAnchorPoint(Image_drop_color, 0.5, 0.5)
GUI:setTag(Image_drop_color, 226)
GUI:setTouchEnabled(Image_drop_color, true)
GUI:setVisible(Image_drop_color, false)

Image_drop = GUI:Image_Create(Image_dropbg, "Image_drop", 30, 12, "res/private/main_win32/chat_input/font_drop.png")
GUI:setAnchorPoint(Image_drop, 0.5, 0.5)
GUI:setContentSize(Image_drop, 32, 14)
GUI:setTag(Image_drop, 85)
GUI:setTouchEnabled(Image_drop, true)

local Image_guildbg = GUI:Layout_Create(ScrollView_chanel, "Image_guildbg", 0, 120, 60, 25, false)
GUI:Layout_setBackGroundColorOpacity(Image_guildbg, 255)
GUI:Layout_setBackGroundImage(Image_guildbg, "")
GUI:setTag(Image_guildbg, 133)
GUI:setTouchEnabled(Image_guildbg, true)

local Image_guild_color = GUI:Layout_Create(Image_guildbg, "Image_guild_color", 30, 12, 50, 25, false)
GUI:Layout_setBackGroundColor(Image_guild_color, "#7BFF3D")
GUI:Layout_setBackGroundColorOpacity(Image_guild_color, 50)
GUI:Layout_setBackGroundColorType(Image_guild_color, 1)
GUI:Layout_setBackGroundImage(Image_guild_color, "")
GUI:setAnchorPoint(Image_guild_color, 0.5, 0.5)
GUI:setTag(Image_guild_color, 227)
GUI:setTouchEnabled(Image_guild_color, true)
GUI:setVisible(Image_guild_color, false)

Image_guild = GUI:Image_Create(Image_guildbg, "Image_guild", 30, 12, "res/private/main_win32/chat_input/font_guild.png")
GUI:setAnchorPoint(Image_guild, 0.5, 0.5)
GUI:setContentSize(Image_guild, 32, 14)
GUI:setTag(Image_guild, 86)
GUI:setTouchEnabled(Image_guild, true)

local Image_privatebg = GUI:Layout_Create(ScrollView_chanel, "Image_privatebg", 0, 100, 60, 25, false)
GUI:Layout_setBackGroundColorOpacity(Image_privatebg, 255)
GUI:Layout_setBackGroundImage(Image_privatebg, "")
GUI:setTag(Image_privatebg, 134)
GUI:setTouchEnabled(Image_privatebg, true)

local Image_private_color = GUI:Layout_Create(Image_privatebg, "Image_private_color", 30, 12, 50, 25, false)
GUI:Layout_setBackGroundColor(Image_private_color, "#7BFF3D")
GUI:Layout_setBackGroundColorOpacity(Image_private_color, 50)
GUI:Layout_setBackGroundColorType(Image_private_color, 1)
GUI:Layout_setBackGroundImage(Image_private_color, "")
GUI:setAnchorPoint(Image_private_color, 0.5, 0.5)
GUI:setTag(Image_private_color, 228)
GUI:setTouchEnabled(Image_private_color, true)
GUI:setVisible(Image_private_color, false)

Image_private = GUI:Image_Create(Image_privatebg, "Image_private", 30, 12, "res/private/main_win32/chat_input/font_person.png")
GUI:setAnchorPoint(Image_private, 0.5, 0.5)
GUI:setContentSize(Image_private, 32, 14)
GUI:setTag(Image_private, 87)
GUI:setTouchEnabled(Image_private, true)

local Image_shoutbg = GUI:Layout_Create(ScrollView_chanel, "Image_shoutbg", 0, 80, 60, 25, false)
GUI:Layout_setBackGroundColorOpacity(Image_shoutbg, 255)
GUI:Layout_setBackGroundImage(Image_shoutbg, "")
GUI:setTag(Image_shoutbg, 135)
GUI:setTouchEnabled(Image_shoutbg, true)

local Image_shout_color = GUI:Layout_Create(Image_shoutbg, "Image_shout_color", 30, 12, 50, 25, false)
GUI:Layout_setBackGroundColor(Image_shout_color, "#7BFF3D")
GUI:Layout_setBackGroundColorOpacity(Image_shout_color, 50)
GUI:Layout_setBackGroundColorType(Image_shout_color, 1)
GUI:Layout_setBackGroundImage(Image_shout_color, "")
GUI:setAnchorPoint(Image_shout_color, 0.5, 0.5)
GUI:setTag(Image_shout_color, 229)
GUI:setTouchEnabled(Image_shout_color, true)
GUI:setVisible(Image_shout_color, false)

Image_shout = GUI:Image_Create(Image_shoutbg, "Image_shout", 30, 12, "res/private/main_win32/chat_input/font_shout.png")
GUI:setAnchorPoint(Image_shout, 0.5, 0.5)
GUI:setContentSize(Image_shout, 32, 14)
GUI:setTag(Image_shout, 88)
GUI:setTouchEnabled(Image_shout, true)

local Image_systembg = GUI:Layout_Create(ScrollView_chanel, "Image_systembg", 0, 60, 60, 25, false)
GUI:Layout_setBackGroundColorOpacity(Image_systembg, 255)
GUI:Layout_setBackGroundImage(Image_systembg, "")
GUI:setTag(Image_systembg, 136)
GUI:setTouchEnabled(Image_systembg, true)

local Image_system_color = GUI:Layout_Create(Image_systembg, "Image_system_color", 30, 12, 50, 25, false)
GUI:Layout_setBackGroundColor(Image_system_color, "#7BFF3D")
GUI:Layout_setBackGroundColorOpacity(Image_system_color, 50)
GUI:Layout_setBackGroundColorType(Image_system_color, 1)
GUI:Layout_setBackGroundImage(Image_system_color, "")
GUI:setAnchorPoint(Image_system_color, 0.5, 0.5)
GUI:setTag(Image_system_color, 230)
GUI:setTouchEnabled(Image_system_color, true)
GUI:setVisible(Image_system_color, false)

Image_system = GUI:Image_Create(Image_systembg, "Image_system", 30, 12, "res/private/main_win32/chat_input/font_system.png")
GUI:setAnchorPoint(Image_system, 0.5, 0.5)
GUI:setContentSize(Image_system, 32, 14)
GUI:setTag(Image_system, 89)
GUI:setTouchEnabled(Image_system, true)

local Image_teambg = GUI:Layout_Create(ScrollView_chanel, "Image_teambg", 0, 40, 60, 25, false)
GUI:Layout_setBackGroundColorOpacity(Image_teambg, 255)
GUI:Layout_setBackGroundImage(Image_teambg, "")
GUI:setTag(Image_teambg, 137)
GUI:setTouchEnabled(Image_teambg, true)

local Image_team_color = GUI:Layout_Create(Image_teambg, "Image_team_color", 30, 12, 50, 25, false)
GUI:Layout_setBackGroundColor(Image_team_color, "#7BFF3D")
GUI:Layout_setBackGroundColorOpacity(Image_team_color, 50)
GUI:Layout_setBackGroundColorType(Image_team_color, 1)
GUI:Layout_setBackGroundImage(Image_team_color, "")
GUI:setAnchorPoint(Image_team_color, 0.5, 0.5)
GUI:setTag(Image_team_color, 231)
GUI:setTouchEnabled(Image_team_color, true)
GUI:setVisible(Image_team_color, false)

Image_team = GUI:Image_Create(Image_teambg, "Image_team", 30, 12, "res/private/main_win32/chat_input/font_team.png")
GUI:setAnchorPoint(Image_team, 0.5, 0.5)
GUI:setContentSize(Image_team, 32, 14)
GUI:setTag(Image_team, 90)
GUI:setTouchEnabled(Image_team, true)

local Image_commonbg = GUI:Layout_Create(ScrollView_chanel, "Image_commonbg", 0, 20, 60, 25, false)
GUI:Layout_setBackGroundColorOpacity(Image_commonbg, 255)
GUI:Layout_setBackGroundImage(Image_commonbg, "")
GUI:setTag(Image_commonbg, 138)
GUI:setTouchEnabled(Image_commonbg, true)

local Image_common_color = GUI:Layout_Create(Image_commonbg, "Image_common_color", 30, 12, 50, 25, false)
GUI:Layout_setBackGroundColor(Image_common_color, "#7BFF3D")
GUI:Layout_setBackGroundColorOpacity(Image_common_color, 50)
GUI:Layout_setBackGroundColorType(Image_common_color, 1)
GUI:Layout_setBackGroundImage(Image_common_color, "")
GUI:setAnchorPoint(Image_common_color, 0.5, 0.5)
GUI:setTag(Image_common_color, 232)
GUI:setTouchEnabled(Image_common_color, true)
GUI:setVisible(Image_common_color, false)

Image_common = GUI:Image_Create(Image_commonbg, "Image_common", 30, 12, "res/private/main_win32/chat_input/font_total.png")
GUI:setAnchorPoint(Image_common, 0.5, 0.5)
GUI:setContentSize(Image_common, 32, 14)
GUI:setTag(Image_common, 91)
GUI:setTouchEnabled(Image_common, true)

local Image_worldbg = GUI:Layout_Create(ScrollView_chanel, "Image_worldbg", 0, 0, 60, 25, false)
GUI:Layout_setBackGroundColorOpacity(Image_worldbg, 255)
GUI:Layout_setBackGroundImage(Image_worldbg, "")
GUI:setTag(Image_worldbg, 139)
GUI:setTouchEnabled(Image_worldbg, true)

local Image_world_color = GUI:Layout_Create(Image_worldbg, "Image_world_color", 30, 12, 50, 25, false)
GUI:Layout_setBackGroundColor(Image_world_color, "#7BFF3D")
GUI:Layout_setBackGroundColorOpacity(Image_world_color, 50)
GUI:Layout_setBackGroundColorType(Image_world_color, 1)
GUI:Layout_setBackGroundImage(Image_world_color, "")
GUI:setAnchorPoint(Image_world_color, 0.5, 0.5)
GUI:setTag(Image_world_color, 233)
GUI:setTouchEnabled(Image_world_color, true)
GUI:setVisible(Image_world_color, false)

Image_world = GUI:Image_Create(Image_worldbg, "Image_world", 30, 12, "res/private/main_win32/chat_input/font_world.png")
GUI:setAnchorPoint(Image_world, 0.5, 0.5)
GUI:setContentSize(Image_world, 32, 14)
GUI:setTag(Image_world, 92)
GUI:setTouchEnabled(Image_world, true)

local listView_bg = GUI:Image_Create(Panel_input, "listView_bg", 0, 33, "res/private/main_win32/chat/img_list_bg.png")
GUI:setContentSize(listView_bg, 150, 210)
GUI:setVisible(listView_bg, false)

local ListView_target = GUI:ListView_Create(listView_bg, "ListView_target", 4, 5, 140, 200, 1)
GUI:Layout_setBackGroundColorOpacity(ListView_target, 255)
GUI:Layout_setBackGroundImage(ListView_target, "")
GUI:Layout_setClippingEnabled(ListView_target, true)
GUI:ListView_setGravity(ListView_target, 5)

local target_item = GUI:Layout_Create(Panel_input, "target_item", 5, 216, 140, 20, false)
GUI:Layout_setBackGroundColorOpacity(target_item, 255)
GUI:Layout_setBackGroundImage(target_item, "")
GUI:setTouchEnabled(target_item, true)
GUI:setVisible(target_item, false)

local targer_select = GUI:Layout_Create(target_item, "targer_select", 0, 0, 140, 20, false)
GUI:Layout_setBackGroundColor(targer_select, "#899A36")
GUI:Layout_setBackGroundColorOpacity(targer_select, 178)
GUI:Layout_setBackGroundColorType(targer_select, 1)
GUI:Layout_setBackGroundImage(targer_select, "")

local target_name = GUI:Text_Create(target_item, "target_name", 0, 0, 16, "#FFFFFF", "玩家名称七个字")
GUI:Text_enableOutline(target_name, "#000000", 0)
GUI:setContentSize(target_name, 140, 20)

 
end 
return ui