local ui = {} 
function ui.init(parent)
local Node = GUI:Node_Create(parent, "Node", 0, 0)

local Panel_1 = GUI:Layout_Create(Node, "Panel_1", 0, 0, 100, 100, false)
GUI:Layout_setBackGroundColorOpacity(Panel_1, 255)
GUI:Layout_setBackGroundImage(Panel_1, "")

local Panel_bg = GUI:Layout_Create(Node, "Panel_bg", -1, 0, 1136, 150, false)
GUI:Layout_setBackGroundColorOpacity(Panel_bg, 255)
GUI:Layout_setBackGroundImage(Panel_bg, "")
GUI:setAnchorPoint(Panel_bg, 0.5, 0)
GUI:setTag(Panel_bg, 222)

local Image_minichat_bg = GUI:Image_Create(Panel_bg, "Image_minichat_bg", 570, 6, "res/private/main/1900012019.png")
GUI:setAnchorPoint(Image_minichat_bg, 0.5, 0)
GUI:setContentSize(Image_minichat_bg, 430, 124)
GUI:setTag(Image_minichat_bg, 238)

local Sp_rainbow = GUI:Image_Create(Panel_bg, "Sp_rainbow", 639, 114, "res/private/main/rainbow_1.png")
GUI:setAnchorPoint(Sp_rainbow, 0.5, 0.5)
GUI:setContentSize(Sp_rainbow, 36, 20)
GUI:setTag(Sp_rainbow, 155)

local btn_rein_add = GUI:Button_Create(Panel_bg, "btn_rein_add", 535, 13, "res/private/main/00641.png")
GUI:Button_loadTextureDisabled(btn_rein_add, "res/private/main/00643.png")
GUI:Button_loadTexturePressed(btn_rein_add, "res/private/main/00641.png")
GUI:Button_setTitleColor(btn_rein_add, "#414146")
GUI:Button_setTitleFontSize(btn_rein_add, 10)
GUI:Button_setTitleText(btn_rein_add, "")
GUI:setAnchorPoint(btn_rein_add, 0.5, 0.5)
GUI:setContentSize(btn_rein_add, 0, 0)
GUI:setTag(btn_rein_add, 128)
GUI:setVisible(btn_rein_add, false)

local Image_exp_bg = GUI:Image_Create(Panel_bg, "Image_exp_bg", 568, 0, "res/private/main/exp_bg.png")
GUI:setAnchorPoint(Image_exp_bg, 0.5, 0)
GUI:setContentSize(Image_exp_bg, 1136, 11)
GUI:setScaleY(Image_exp_bg, 0.5)
GUI:setTag(Image_exp_bg, 281)

local LoadingBar_exp = GUI:LoadingBar_Create(Panel_bg, "LoadingBar_exp", 568, 3, "res/private/main/1900012010.png", 100)
GUI:LoadingBar_setPercent(LoadingBar_exp, 100)
GUI:setAnchorPoint(LoadingBar_exp, 0.5, 0)
GUI:setContentSize(LoadingBar_exp, 1136, 11)
GUI:setScaleY(LoadingBar_exp, 0.5)
GUI:setTag(LoadingBar_exp, 282)

local Image_exp_mask = GUI:Image_Create(Panel_bg, "Image_exp_mask", 568, 0, "res/private/main/exp_bg2.png")
GUI:setAnchorPoint(Image_exp_mask, 0.5, 0)
GUI:setContentSize(Image_exp_mask, 1136, 11)
GUI:setScaleY(Image_exp_mask, 0.5)
GUI:setTag(Image_exp_mask, 82)

local Image_net = GUI:Image_Create(Panel_bg, "Image_net", 87, 12, "res/private/main/Other/1900012501.png")
GUI:setAnchorPoint(Image_net, 0.5, 0.5)
GUI:setContentSize(Image_net, 27, 24)
GUI:setScaleX(Image_net, 0.5)
GUI:setScaleY(Image_net, 0.5)
GUI:setTag(Image_net, 58)

local Image_battery = GUI:Image_Create(Panel_bg, "Image_battery", 109, 13, "res/private/main/Other/1900012502.png")
GUI:setAnchorPoint(Image_battery, 0.5, 0.5)
GUI:setContentSize(Image_battery, 49, 23)
GUI:setScaleX(Image_battery, 0.5)
GUI:setScaleY(Image_battery, 0.5)
GUI:setTag(Image_battery, 57)

local LoadingBar_battery = GUI:LoadingBar_Create(Panel_bg, "LoadingBar_battery", 108, 17, "res/private/main/Other/1900012503.png", 100)
GUI:LoadingBar_setPercent(LoadingBar_battery, 100)
GUI:setAnchorPoint(LoadingBar_battery, 0.5, 0.5)
GUI:setContentSize(LoadingBar_battery, 39, 15)
GUI:setScaleX(LoadingBar_battery, 0.5)
GUI:setScaleY(LoadingBar_battery, 0.5)
GUI:setTag(LoadingBar_battery, 56)

local Panel_hp = GUI:Layout_Create(Panel_bg, "Panel_hp", 415, 59, 70, 70, false)
GUI:Layout_setBackGroundColorOpacity(Panel_hp, 255)
GUI:Layout_setBackGroundImage(Panel_hp, "")
GUI:setAnchorPoint(Panel_hp, 0.5, 0.5)
GUI:setTag(Panel_hp, 35)
GUI:setTouchEnabled(Panel_hp, true)

local Image_divide = GUI:Image_Create(Panel_hp, "Image_divide", 35, 35, "res/private/main/1900012507.png")
GUI:setAnchorPoint(Image_divide, 0.5, 0.5)
GUI:setContentSize(Image_divide, 0, 0)
GUI:setTag(Image_divide, 55)

local LoadingBar_hp = GUI:LoadingBar_Create(Panel_hp, "LoadingBar_hp", 16, 32, "res/private/main/1900012032.png", 0)
GUI:LoadingBar_setPercent(LoadingBar_hp, 100)
GUI:setAnchorPoint(LoadingBar_hp, 0.5, 0.5)
GUI:setContentSize(LoadingBar_hp, 88, 40)
GUI:setRotation(LoadingBar_hp, 270)
GUI:setRotationSkewX(LoadingBar_hp, 270)
GUI:setRotationSkewY(LoadingBar_hp, 270)
GUI:setTag(LoadingBar_hp, 226)

local LoadingBar_mp = GUI:LoadingBar_Create(Panel_hp, "LoadingBar_mp", 57, 32, "res/private/main/1900012033.png", 0)
GUI:LoadingBar_setPercent(LoadingBar_mp, 100)
GUI:setAnchorPoint(LoadingBar_mp, 0.5, 0.5)
GUI:setContentSize(LoadingBar_mp, 88, 40)
GUI:setRotation(LoadingBar_mp, 270)
GUI:setRotationSkewX(LoadingBar_mp, 270)
GUI:setRotationSkewY(LoadingBar_mp, 270)
GUI:setTag(LoadingBar_mp, 227)

local LoadingBar_fhp = GUI:LoadingBar_Create(Panel_hp, "LoadingBar_fhp", -6, 32, "res/private/main/1900012504.png", 0)
GUI:LoadingBar_setPercent(LoadingBar_fhp, 100)
GUI:setAnchorPoint(LoadingBar_fhp, 0.5, 0.5)
GUI:setContentSize(LoadingBar_fhp, 88, 82)
GUI:setRotation(LoadingBar_fhp, 270)
GUI:setRotationSkewX(LoadingBar_fhp, 270)
GUI:setRotationSkewY(LoadingBar_fhp, 270)
GUI:setTag(LoadingBar_fhp, 32)
GUI:setVisible(LoadingBar_fhp, false)

local Panel_hp_sfx = GUI:Layout_Create(Panel_hp, "Panel_hp_sfx", 0, 0, 33, 70, true)
GUI:Layout_setBackGroundColorOpacity(Panel_hp_sfx, 255)
GUI:Layout_setBackGroundImage(Panel_hp_sfx, "")
GUI:setTag(Panel_hp_sfx, 47)

local Panel_mp_sfx = GUI:Layout_Create(Panel_hp, "Panel_mp_sfx", 37, 0, 33, 70, true)
GUI:Layout_setBackGroundColorOpacity(Panel_mp_sfx, 255)
GUI:Layout_setBackGroundImage(Panel_mp_sfx, "")
GUI:setTag(Panel_mp_sfx, 48)

local Panel_fhp_sfx = GUI:Layout_Create(Panel_hp, "Panel_fhp_sfx", 0, 0, 70, 70, true)
GUI:Layout_setBackGroundColorOpacity(Panel_fhp_sfx, 255)
GUI:Layout_setBackGroundImage(Panel_fhp_sfx, "")
GUI:setTag(Panel_fhp_sfx, 49)

local Panel_hp_touch = GUI:Layout_Create(Panel_hp, "Panel_hp_touch", -1, -11, 74, 90, false)
GUI:Layout_setBackGroundColorOpacity(Panel_hp_touch, 255)
GUI:Layout_setBackGroundImage(Panel_hp_touch, "")
GUI:setTag(Panel_hp_touch, 82)
GUI:setTouchEnabled(Panel_hp_touch, true)

local Panel_mp_touch = GUI:Layout_Create(Panel_hp, "Panel_mp_touch", 37, -11, 35, 90, false)
GUI:Layout_setBackGroundColorOpacity(Panel_mp_touch, 255)
GUI:Layout_setBackGroundImage(Panel_mp_touch, "")
GUI:setTag(Panel_mp_touch, 83)
GUI:setTouchEnabled(Panel_mp_touch, true)

local Image_4 = GUI:Image_Create(Panel_bg, "Image_4", 417, 4, "res/private/main/1900012000.png")
GUI:setAnchorPoint(Image_4, 0.5, 0)
GUI:setContentSize(Image_4, 154, 107)
GUI:setTag(Image_4, 228)

local Panel_hp_bg = GUI:Layout_Create(Panel_bg, "Panel_hp_bg", 394, 64, 76, 15, false)
GUI:Layout_setBackGroundColor(Panel_hp_bg, "#FF0500")
GUI:Layout_setBackGroundColorOpacity(Panel_hp_bg, 229)
GUI:Layout_setBackGroundColorType(Panel_hp_bg, 1)
GUI:Layout_setBackGroundImage(Panel_hp_bg, "")
GUI:setAnchorPoint(Panel_hp_bg, 0.5, 0)
GUI:setTag(Panel_hp_bg, 80)
GUI:setVisible(Panel_hp_bg, false)

local Text_hp = GUI:Text_Create(Panel_hp_bg, "Text_hp", 0, 0, 14, "#FFFFFF", "(体力)11/11")
GUI:Text_enableOutline(Text_hp, "#000000", 0)
GUI:setContentSize(Text_hp, 76, 16)
GUI:setIgnoreContentAdaptWithSize(Text_hp, true)
GUI:setTag(Text_hp, 275)

local Panel_mp_bg = GUI:Layout_Create(Panel_bg, "Panel_mp_bg", 442, 39, 68, 15, false)
GUI:Layout_setBackGroundColor(Panel_mp_bg, "#0000FF")
GUI:Layout_setBackGroundColorOpacity(Panel_mp_bg, 229)
GUI:Layout_setBackGroundColorType(Panel_mp_bg, 1)
GUI:Layout_setBackGroundImage(Panel_mp_bg, "")
GUI:setAnchorPoint(Panel_mp_bg, 0.5, 0)
GUI:setTag(Panel_mp_bg, 81)
GUI:setVisible(Panel_mp_bg, false)

local Text_mp = GUI:Text_Create(Panel_mp_bg, "Text_mp", 0, 0, 14, "#FFFFFF", "(法力)2/14")
GUI:Text_enableOutline(Text_mp, "#000000", 0)
GUI:setContentSize(Text_mp, 68, 16)
GUI:setIgnoreContentAdaptWithSize(Text_mp, true)
GUI:setTag(Text_mp, 276)

local Text_level = GUI:Text_Create(Panel_bg, "Text_level", 638, 106, 14, "#FFFF00", "10")
GUI:Text_enableOutline(Text_level, "#000000", 0)
GUI:setAnchorPoint(Text_level, 0.5, 0.5)
GUI:setContentSize(Text_level, 16, 16)
GUI:setIgnoreContentAdaptWithSize(Text_level, true)
GUI:setTag(Text_level, 279)

local Text_time = GUI:Text_Create(Panel_bg, "Text_time", 1081, -194, 16, "#FFFFFF", "-")
GUI:Text_enableOutline(Text_time, "#000000", 0)
GUI:setAnchorPoint(Text_time, 0.5, 0.5)
GUI:setContentSize(Text_time, 6, 18)
GUI:setIgnoreContentAdaptWithSize(Text_time, true)
GUI:setTag(Text_time, 46)

local Text_exp = GUI:Text_Create(Panel_bg, "Text_exp", 126, 16, 14, "#44DDFF", "0%")
GUI:Text_enableOutline(Text_exp, "#000000", 1)
GUI:setAnchorPoint(Text_exp, 0, 0.5)
GUI:setContentSize(Text_exp, 22, 18)
GUI:setIgnoreContentAdaptWithSize(Text_exp, true)
GUI:setTag(Text_exp, 59)

local Panel_mini_chat = GUI:Layout_Create(Node, "Panel_mini_chat", -68, 13, 277, 83, false)
GUI:Layout_setBackGroundColorOpacity(Panel_mini_chat, 255)
GUI:Layout_setBackGroundImage(Panel_mini_chat, "")
GUI:setTag(Panel_mini_chat, 237)
GUI:setTouchEnabled(Panel_mini_chat, true)

local Panel_mini_chat_touch = GUI:Layout_Create(Panel_mini_chat, "Panel_mini_chat_touch", 0, 0, 277, 83, false)
GUI:Layout_setBackGroundColorOpacity(Panel_mini_chat_touch, 255)
GUI:Layout_setBackGroundImage(Panel_mini_chat_touch, "")
GUI:setTag(Panel_mini_chat_touch, 47)
GUI:setTouchEnabled(Panel_mini_chat_touch, true)

local ListView_minichat = GUI:ListView_Create(Panel_mini_chat, "ListView_minichat", 0, 0, 277, 83, 1)
GUI:Layout_setBackGroundColorOpacity(ListView_minichat, 255)
GUI:Layout_setBackGroundImage(ListView_minichat, "")
GUI:Layout_setClippingEnabled(ListView_minichat, true)
GUI:ListView_setGravity(ListView_minichat, 5)
GUI:setTag(ListView_minichat, 239)
GUI:setTouchEnabled(ListView_minichat, false)

local ListView_chat_ex = GUI:ListView_Create(Panel_mini_chat, "ListView_chat_ex", 136, 82, 274, 25, 1)
GUI:Layout_setBackGroundColorOpacity(ListView_chat_ex, 255)
GUI:Layout_setBackGroundImage(ListView_chat_ex, "")
GUI:Layout_setClippingEnabled(ListView_chat_ex, true)
GUI:ListView_setGravity(ListView_chat_ex, 5)
GUI:setAnchorPoint(ListView_chat_ex, 0.5, 1)
GUI:setTag(ListView_chat_ex, 40)
GUI:setTouchEnabled(ListView_chat_ex, false)

local Panel_quick_use = GUI:Layout_Create(Node, "Panel_quick_use", -90, 118, 316, 50, false)
GUI:Layout_setBackGroundColorOpacity(Panel_quick_use, 255)
GUI:Layout_setBackGroundImage(Panel_quick_use, "")
GUI:setTag(Panel_quick_use, 118)

local Panel_quick_use_1 = GUI:Layout_Create(Panel_quick_use, "Panel_quick_use_1", 13, 0, 50, 50, false)
GUI:Layout_setBackGroundColorOpacity(Panel_quick_use_1, 255)
GUI:Layout_setBackGroundImage(Panel_quick_use_1, "")
GUI:setScaleX(Panel_quick_use_1, 0.80000001192093)
GUI:setScaleY(Panel_quick_use_1, 0.80000001192093)
GUI:setTag(Panel_quick_use_1, 135)
GUI:setTouchEnabled(Panel_quick_use_1, true)

local Panel_quick_use_2 = GUI:Layout_Create(Panel_quick_use, "Panel_quick_use_2", 63, 0, 50, 50, false)
GUI:Layout_setBackGroundColorOpacity(Panel_quick_use_2, 255)
GUI:Layout_setBackGroundImage(Panel_quick_use_2, "")
GUI:setScaleX(Panel_quick_use_2, 0.80000001192093)
GUI:setScaleY(Panel_quick_use_2, 0.80000001192093)
GUI:setTag(Panel_quick_use_2, 136)
GUI:setTouchEnabled(Panel_quick_use_2, true)

local Panel_quick_use_3 = GUI:Layout_Create(Panel_quick_use, "Panel_quick_use_3", 113, 0, 50, 50, false)
GUI:Layout_setBackGroundColorOpacity(Panel_quick_use_3, 255)
GUI:Layout_setBackGroundImage(Panel_quick_use_3, "")
GUI:setScaleX(Panel_quick_use_3, 0.80000001192093)
GUI:setScaleY(Panel_quick_use_3, 0.80000001192093)
GUI:setTag(Panel_quick_use_3, 137)
GUI:setTouchEnabled(Panel_quick_use_3, true)

local Panel_quick_use_4 = GUI:Layout_Create(Panel_quick_use, "Panel_quick_use_4", 164, 0, 50, 50, false)
GUI:Layout_setBackGroundColorOpacity(Panel_quick_use_4, 255)
GUI:Layout_setBackGroundImage(Panel_quick_use_4, "")
GUI:setScaleX(Panel_quick_use_4, 0.80000001192093)
GUI:setScaleY(Panel_quick_use_4, 0.80000001192093)
GUI:setTag(Panel_quick_use_4, 138)
GUI:setTouchEnabled(Panel_quick_use_4, true)

local Panel_quick_use_5 = GUI:Layout_Create(Panel_quick_use, "Panel_quick_use_5", 214, 0, 50, 50, false)
GUI:Layout_setBackGroundColorOpacity(Panel_quick_use_5, 255)
GUI:Layout_setBackGroundImage(Panel_quick_use_5, "")
GUI:setScaleX(Panel_quick_use_5, 0.80000001192093)
GUI:setScaleY(Panel_quick_use_5, 0.80000001192093)
GUI:setTag(Panel_quick_use_5, 139)
GUI:setTouchEnabled(Panel_quick_use_5, true)

local Panel_quick_use_6 = GUI:Layout_Create(Panel_quick_use, "Panel_quick_use_6", 264, 0, 50, 50, false)
GUI:Layout_setBackGroundColorOpacity(Panel_quick_use_6, 255)
GUI:Layout_setBackGroundImage(Panel_quick_use_6, "")
GUI:setScaleX(Panel_quick_use_6, 0.80000001192093)
GUI:setScaleY(Panel_quick_use_6, 0.80000001192093)
GUI:setTag(Panel_quick_use_6, 140)
GUI:setTouchEnabled(Panel_quick_use_6, true)

local Panel_bubble_tips = GUI:Layout_Create(Node, "Panel_bubble_tips", -159, 147, 150, 50, false)
GUI:Layout_setBackGroundColorOpacity(Panel_bubble_tips, 255)
GUI:Layout_setBackGroundImage(Panel_bubble_tips, "")
GUI:setAnchorPoint(Panel_bubble_tips, 0.5, 0)
GUI:setTag(Panel_bubble_tips, 41)

local ListView_bubble_tips = GUI:ListView_Create(Panel_bubble_tips, "ListView_bubble_tips", 0, -7, 150, 50, 2)
GUI:Layout_setBackGroundColorOpacity(ListView_bubble_tips, 255)
GUI:Layout_setBackGroundImage(ListView_bubble_tips, "")
GUI:Layout_setClippingEnabled(ListView_bubble_tips, true)
GUI:ListView_setGravity(ListView_bubble_tips, 3)
GUI:setTag(ListView_bubble_tips, 42)
GUI:setTouchEnabled(ListView_bubble_tips, false)

local ListView_SkillStateTips = GUI:ListView_Create(Node, "ListView_SkillStateTips", -85, 153, 290, 60, 2)
GUI:Layout_setBackGroundColorOpacity(ListView_SkillStateTips, 255)
GUI:Layout_setBackGroundImage(ListView_SkillStateTips, "")
GUI:Layout_setClippingEnabled(ListView_SkillStateTips, true)
GUI:ListView_setGravity(ListView_SkillStateTips, 3)
GUI:setTag(ListView_SkillStateTips, 62)
GUI:setTouchEnabled(ListView_SkillStateTips, false)

local Panel_SkillState_item = GUI:Layout_Create(Node, "Panel_SkillState_item", -64, 155, 50, 60, false)
GUI:Layout_setBackGroundColorOpacity(Panel_SkillState_item, 255)
GUI:Layout_setBackGroundImage(Panel_SkillState_item, "")
GUI:setTag(Panel_SkillState_item, 101)
GUI:setVisible(Panel_SkillState_item, false)

local Image_icon = GUI:Image_Create(Panel_SkillState_item, "Image_icon", 25, 21, "Default/ImageFile.png")
GUI:setAnchorPoint(Image_icon, 0.5, 0.5)
GUI:setContentSize(Image_icon, 30, 30)
GUI:setTag(Image_icon, 100)

Text_time = GUI:Text_Create(Panel_SkillState_item, "Text_time", 25, 51, 18, "#FFFFFF", "20S")
GUI:Text_enableOutline(Text_time, "#000000", 0)
GUI:setAnchorPoint(Text_time, 0.5, 0.5)
GUI:setContentSize(Text_time, 32, 20)
GUI:setIgnoreContentAdaptWithSize(Text_time, true)
GUI:setTag(Text_time, 102)

local Panel_auto_tips = GUI:Layout_Create(Node, "Panel_auto_tips", -51, 224, 316, 60, false)
GUI:Layout_setBackGroundColorOpacity(Panel_auto_tips, 255)
GUI:Layout_setBackGroundImage(Panel_auto_tips, "")
GUI:setAnchorPoint(Panel_auto_tips, 0.5, 0)
GUI:setTag(Panel_auto_tips, 85)

local Button_ride = GUI:Button_Create(Node, "Button_ride", -256, 47, "res/private/main/Skill/1900012711.png")
GUI:Button_loadTextureDisabled(Button_ride, "Default/Button_Disable.png")
GUI:Button_setTitleColor(Button_ride, "#414146")
GUI:Button_setTitleFontSize(Button_ride, 10)
GUI:Button_setTitleText(Button_ride, "")
GUI:setAnchorPoint(Button_ride, 0.5, 0.5)
GUI:setContentSize(Button_ride, 50, 50)
GUI:setTag(Button_ride, 49)

local Button_ring = GUI:Button_Create(Node, "Button_ring", -322, 47, "res/private/main/Skill/1900012710.png")
GUI:Button_loadTextureDisabled(Button_ring, "Default/Button_Disable.png")
GUI:Button_setTitleColor(Button_ring, "#414146")
GUI:Button_setTitleFontSize(Button_ring, 10)
GUI:Button_setTitleText(Button_ring, "")
GUI:setAnchorPoint(Button_ring, 0.5, 0.5)
GUI:setContentSize(Button_ring, 52, 52)
GUI:setTag(Button_ring, 50)

 
end 
return ui