local ui = {} 
function ui.init(parent)
local Node = GUI:Node_Create(parent, "Node", 0, 0)

local panel_1 = GUI:Layout_Create(Node, "panel_1", 0, 0, 170, 150, false)
GUI:Layout_setBackGroundColorOpacity(panel_1, 255)
GUI:Layout_setBackGroundImage(panel_1, "")
GUI:setAnchorPoint(panel_1, 1, 1)

local Panel_map = GUI:Layout_Create(panel_1, "Panel_map", 170, 150, 143, 160, false)
GUI:Layout_setBackGroundColorOpacity(Panel_map, 255)
GUI:Layout_setBackGroundImage(Panel_map, "")
GUI:setAnchorPoint(Panel_map, 1, 1)
GUI:setTag(Panel_map, 47)
GUI:setTouchEnabled(Panel_map, true)

local Panel_minimap = GUI:Layout_Create(Panel_map, "Panel_minimap", 56, 130, 162, 117, true)
GUI:Layout_setBackGroundColorOpacity(Panel_minimap, 255)
GUI:Layout_setBackGroundImage(Panel_minimap, "")
GUI:setAnchorPoint(Panel_minimap, 0.5, 1)
GUI:setTag(Panel_minimap, 22)
GUI:setTouchEnabled(Panel_minimap, true)

local Image_minimap = GUI:Image_Create(Panel_minimap, "Image_minimap", 0, 0, "Default/ImageFile.png")
GUI:setContentSize(Image_minimap, 46, 46)
GUI:setTag(Image_minimap, 46)

local Node_npc = GUI:Node_Create(Image_minimap, "Node_npc", 0, 0)
GUI:setTag(Node_npc, 46)

local Node_actors = GUI:Node_Create(Image_minimap, "Node_actors", 0, 0)
GUI:setTag(Node_actors, 40)

local Node_path = GUI:Node_Create(Image_minimap, "Node_path", 0, 0)
GUI:setTag(Node_path, 139)

local Node_sfx = GUI:Node_Create(Image_minimap, "Node_sfx", 10, -10)
GUI:setTag(Node_sfx, 35)

local Node_player = GUI:Node_Create(Panel_minimap, "Node_player", -29, 11)
GUI:setTag(Node_player, 23)

local Image_empty = GUI:Image_Create(Panel_map, "Image_empty", 56, 131, "res/private/main/miniMap/1900012102.png")
GUI:setAnchorPoint(Image_empty, 0.5, 1)
GUI:setContentSize(Image_empty, 164, 117)
GUI:setTag(Image_empty, 15)

local Image_frame = GUI:Image_Create(Panel_map, "Image_frame", 143, 160, "res/private/main/miniMap/1900012101.png")
GUI:Image_setScale9Enabled(Image_frame, true)
GUI:Image_setScale9Slice(Image_frame, 0, 0, 40, 10)
GUI:setAnchorPoint(Image_frame, 1, 1)
GUI:setContentSize(Image_frame, 174, 151)
GUI:setTag(Image_frame, 258)

local Panel_map_bg = GUI:Layout_Create(Image_frame, "Panel_map_bg", 87, 5, 163, 17, false)
GUI:Layout_setBackGroundColor(Panel_map_bg, "#000000")
GUI:Layout_setBackGroundColorOpacity(Panel_map_bg, 102)
GUI:Layout_setBackGroundColorType(Panel_map_bg, 1)
GUI:Layout_setBackGroundImage(Panel_map_bg, "")
GUI:setAnchorPoint(Panel_map_bg, 0.5, 0)
GUI:setTag(Panel_map_bg, 79)

local Text_position = GUI:Text_Create(Panel_map_bg, "Text_position", 81, 9, 14, "#FFFFFF", "550:550")
GUI:Text_enableOutline(Text_position, "#000000", 0)
GUI:setAnchorPoint(Text_position, 0.5, 0.5)
GUI:setContentSize(Text_position, 52, 16)
GUI:setIgnoreContentAdaptWithSize(Text_position, true)
GUI:setTag(Text_position, 10)

local Panel_bg = GUI:Layout_Create(Panel_map, "Panel_bg", 9, 132, 104, 23, false)
GUI:Layout_setBackGroundColor(Panel_bg, "#000000")
GUI:Layout_setBackGroundColorOpacity(Panel_bg, 204)
GUI:Layout_setBackGroundColorType(Panel_bg, 1)
GUI:Layout_setBackGroundImage(Panel_bg, "")
GUI:setTag(Panel_bg, 237)

local Image_di2 = GUI:Image_Create(Panel_map, "Image_di2", -9, 143, "res/private/main/miniMap/img_di1.png")
GUI:setAnchorPoint(Image_di2, 0.5, 0.5)
GUI:setContentSize(Image_di2, 32, 22)
GUI:setTag(Image_di2, 52)

local Text_area = GUI:Text_Create(Panel_map, "Text_area", -24, 143, 14, "#FFFFFF", "安全")
GUI:Text_enableOutline(Text_area, "#000000", 1)
GUI:setAnchorPoint(Text_area, 0, 0.5)
GUI:setContentSize(Text_area, 28, 18)
GUI:setIgnoreContentAdaptWithSize(Text_area, true)
GUI:setTag(Text_area, 8)

local Button_map = GUI:Layout_Create(Panel_map, "Button_map", -25, 132, 163, 22, false)
GUI:Layout_setBackGroundColorOpacity(Button_map, 255)
GUI:Layout_setBackGroundImage(Button_map, "")
GUI:setTag(Button_map, 585)
GUI:setTouchEnabled(Button_map, true)

local Image_type = GUI:Image_Create(Button_map, "Image_type", 162, 11, "res/private/main/miniMap/btn_min2.png")
GUI:setAnchorPoint(Image_type, 1, 0.5)
GUI:setContentSize(Image_type, 21, 21)
GUI:setTag(Image_type, 586)

local Text_map_name = GUI:Text_Create(Panel_map, "Text_map_name", 60, 143, 16, "#FFFFFF", "比奇省")
GUI:Text_enableOutline(Text_map_name, "#000000", 0)
GUI:setAnchorPoint(Text_map_name, 0.5, 0.5)
GUI:setContentSize(Text_map_name, 48, 18)
GUI:setIgnoreContentAdaptWithSize(Text_map_name, true)
GUI:setTag(Text_map_name, 45)

local Panel_pkmode = GUI:Layout_Create(panel_1, "Panel_pkmode", 0, 149, 45, 80, false)
GUI:Layout_setBackGroundColorOpacity(Panel_pkmode, 255)
GUI:Layout_setBackGroundImage(Panel_pkmode, "")
GUI:setAnchorPoint(Panel_pkmode, 1, 1)
GUI:setTag(Panel_pkmode, 48)
GUI:setTouchEnabled(Panel_pkmode, true)

local Panel_cells = GUI:Layout_Create(Panel_pkmode, "Panel_cells", 42, 40, 200, 79, false)
GUI:Layout_setBackGroundColorOpacity(Panel_cells, 255)
GUI:Layout_setBackGroundImage(Panel_cells, "")
GUI:setAnchorPoint(Panel_cells, 1, 0.5)
GUI:setTag(Panel_cells, 59)

local Button_mode = GUI:Button_Create(Panel_pkmode, "Button_mode", 45, 40, "res/private/main/Button/1900012153.png")
GUI:Button_loadTexturePressed(Button_mode, "res/private/main/Button/1900012152.png")
GUI:Button_setTitleColor(Button_mode, "#414146")
GUI:Button_setTitleFontSize(Button_mode, 10)
GUI:Button_setTitleText(Button_mode, "")
GUI:setAnchorPoint(Button_mode, 1, 0.5)
GUI:setContentSize(Button_mode, 0, 0)
GUI:setTag(Button_mode, 49)

local Image_mode = GUI:Image_Create(Button_mode, "Image_mode", 23, 40, "res/private/main/Pattern/1900012200.png")
GUI:setAnchorPoint(Image_mode, 0.5, 0.5)
GUI:setContentSize(Image_mode, 22, 45)
GUI:setTag(Image_mode, 50)

local Panel_tips = GUI:Layout_Create(panel_1, "Panel_tips", -14, -6, 28, 30, false)
GUI:Layout_setBackGroundColorOpacity(Panel_tips, 255)
GUI:Layout_setBackGroundImage(Panel_tips, "")
GUI:setTag(Panel_tips, 34)
GUI:setTouchEnabled(Panel_tips, true)
GUI:setVisible(Panel_tips, false)

local ScrollView_tips = GUI:ScrollView_Create(Panel_tips, "ScrollView_tips", 0, 0, 204, 54, 1)
GUI:Layout_setBackGroundColorOpacity(ScrollView_tips, 255)
GUI:Layout_setBackGroundImage(ScrollView_tips, "")
GUI:Layout_setClippingEnabled(ScrollView_tips, true)
GUI:ScrollView_setBounceEnabled(ScrollView_tips, true)
GUI:ScrollView_setInnerContainerSize(ScrollView_tips, 204, 180)
GUI:setAnchorPoint(ScrollView_tips, 0, 1)
GUI:setTag(ScrollView_tips, 23)
GUI:setTouchEnabled(ScrollView_tips, true)

local Text_1 = GUI:Text_Create(ScrollView_tips, "Text_1", 0, 178, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_1, "#000000", 0)
GUI:setAnchorPoint(Text_1, 0, 1)
GUI:setContentSize(Text_1, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_1, true)
GUI:setTag(Text_1, 24)

local Text_2 = GUI:Text_Create(ScrollView_tips, "Text_2", 0, 160, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_2, "#000000", 0)
GUI:setAnchorPoint(Text_2, 0, 1)
GUI:setContentSize(Text_2, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_2, true)
GUI:setTag(Text_2, 26)

local Text_3 = GUI:Text_Create(ScrollView_tips, "Text_3", 0, 143, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_3, "#000000", 0)
GUI:setAnchorPoint(Text_3, 0, 1)
GUI:setContentSize(Text_3, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_3, true)
GUI:setTag(Text_3, 25)

local Text_4 = GUI:Text_Create(ScrollView_tips, "Text_4", 0, 125, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_4, "#000000", 0)
GUI:setAnchorPoint(Text_4, 0, 1)
GUI:setContentSize(Text_4, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_4, true)
GUI:setTag(Text_4, 27)

local Text_5 = GUI:Text_Create(ScrollView_tips, "Text_5", 0, 107, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_5, "#000000", 0)
GUI:setAnchorPoint(Text_5, 0, 1)
GUI:setContentSize(Text_5, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_5, true)
GUI:setTag(Text_5, 28)

local Text_6 = GUI:Text_Create(ScrollView_tips, "Text_6", 0, 90, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_6, "#000000", 0)
GUI:setAnchorPoint(Text_6, 0, 1)
GUI:setContentSize(Text_6, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_6, true)
GUI:setTag(Text_6, 29)

local Text_7 = GUI:Text_Create(ScrollView_tips, "Text_7", 0, 72, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_7, "#000000", 0)
GUI:setAnchorPoint(Text_7, 0, 1)
GUI:setContentSize(Text_7, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_7, true)
GUI:setTag(Text_7, 30)

local Text_8 = GUI:Text_Create(ScrollView_tips, "Text_8", 0, 55, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_8, "#000000", 0)
GUI:setAnchorPoint(Text_8, 0, 1)
GUI:setContentSize(Text_8, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_8, true)
GUI:setTag(Text_8, 31)

local Text_9 = GUI:Text_Create(ScrollView_tips, "Text_9", 0, 37, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_9, "#000000", 0)
GUI:setAnchorPoint(Text_9, 0, 1)
GUI:setContentSize(Text_9, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_9, true)
GUI:setTag(Text_9, 32)

local Text_10 = GUI:Text_Create(ScrollView_tips, "Text_10", 0, 19, 14, "#FFFFFF", "地图名名下次开启时间 00：00")
GUI:Text_enableOutline(Text_10, "#000000", 0)
GUI:setAnchorPoint(Text_10, 0, 1)
GUI:setContentSize(Text_10, 190, 16)
GUI:setIgnoreContentAdaptWithSize(Text_10, true)
GUI:setTag(Text_10, 33)

 
end 
return ui